// Code generated by go-swagger; DO NOT EDIT.

package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api/models"
)

// CreateanewPartyCallControlReader is a Reader for the CreateanewPartyCallControl structure.
type CreateanewPartyCallControlReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateanewPartyCallControlReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateanewPartyCallControlCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewCreateanewPartyCallControlUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateanewPartyCallControlCreated creates a CreateanewPartyCallControlCreated with default headers values
func NewCreateanewPartyCallControlCreated() *CreateanewPartyCallControlCreated {
	return &CreateanewPartyCallControlCreated{
		Location: "nostrud velit non",
	}
}

/*CreateanewPartyCallControlCreated handles this case with default header values.

CreateanewPartyCallControlCreated createanew party call control created
*/
type CreateanewPartyCallControlCreated struct {
	Location string

	Payload []*models.Thenewlycreateditemorempty55
}

func (o *CreateanewPartyCallControlCreated) Error() string {
	return fmt.Sprintf("[POST /partycallcontrols][%d] createanewPartyCallControlCreated  %+v", 201, o.Payload)
}

func (o *CreateanewPartyCallControlCreated) GetPayload() []*models.Thenewlycreateditemorempty55 {
	return o.Payload
}

func (o *CreateanewPartyCallControlCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Location
	o.Location = response.GetHeader("Location")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateanewPartyCallControlUnprocessableEntity creates a CreateanewPartyCallControlUnprocessableEntity with default headers values
func NewCreateanewPartyCallControlUnprocessableEntity() *CreateanewPartyCallControlUnprocessableEntity {
	return &CreateanewPartyCallControlUnprocessableEntity{}
}

/*CreateanewPartyCallControlUnprocessableEntity handles this case with default header values.

Unprocessable Entity (WebDAV) (RFC 4918)
*/
type CreateanewPartyCallControlUnprocessableEntity struct {
	Payload *models.Anerror
}

func (o *CreateanewPartyCallControlUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /partycallcontrols][%d] createanewPartyCallControlUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateanewPartyCallControlUnprocessableEntity) GetPayload() *models.Anerror {
	return o.Payload
}

func (o *CreateanewPartyCallControlUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Anerror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
