// Code generated by go-swagger; DO NOT EDIT.

package interceptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api1/models"
)

// NewCreateanewInterceptionParams creates a new CreateanewInterceptionParams object
// with the default values initialized.
func NewCreateanewInterceptionParams() *CreateanewInterceptionParams {
	var ()
	return &CreateanewInterceptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateanewInterceptionParamsWithTimeout creates a new CreateanewInterceptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateanewInterceptionParamsWithTimeout(timeout time.Duration) *CreateanewInterceptionParams {
	var ()
	return &CreateanewInterceptionParams{

		timeout: timeout,
	}
}

// NewCreateanewInterceptionParamsWithContext creates a new CreateanewInterceptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateanewInterceptionParamsWithContext(ctx context.Context) *CreateanewInterceptionParams {
	var ()
	return &CreateanewInterceptionParams{

		Context: ctx,
	}
}

// NewCreateanewInterceptionParamsWithHTTPClient creates a new CreateanewInterceptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateanewInterceptionParamsWithHTTPClient(client *http.Client) *CreateanewInterceptionParams {
	var ()
	return &CreateanewInterceptionParams{
		HTTPClient: client,
	}
}

/*CreateanewInterceptionParams contains all the parameters to send to the API endpoint
for the createanew interception operation typically these are written to a http.Request
*/
type CreateanewInterceptionParams struct {

	/*Body*/
	Body *models.CreateanewInterceptionRequest
	/*ContentType*/
	ContentType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the createanew interception params
func (o *CreateanewInterceptionParams) WithTimeout(timeout time.Duration) *CreateanewInterceptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the createanew interception params
func (o *CreateanewInterceptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the createanew interception params
func (o *CreateanewInterceptionParams) WithContext(ctx context.Context) *CreateanewInterceptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the createanew interception params
func (o *CreateanewInterceptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the createanew interception params
func (o *CreateanewInterceptionParams) WithHTTPClient(client *http.Client) *CreateanewInterceptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the createanew interception params
func (o *CreateanewInterceptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the createanew interception params
func (o *CreateanewInterceptionParams) WithBody(body *models.CreateanewInterceptionRequest) *CreateanewInterceptionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the createanew interception params
func (o *CreateanewInterceptionParams) SetBody(body *models.CreateanewInterceptionRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the createanew interception params
func (o *CreateanewInterceptionParams) WithContentType(contentType string) *CreateanewInterceptionParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the createanew interception params
func (o *CreateanewInterceptionParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WriteToRequest writes these params to a swagger request
func (o *CreateanewInterceptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
