// Code generated by go-swagger; DO NOT EDIT.

package customerzonecosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCustomerZoneCostitemsParams creates a new GetCustomerZoneCostitemsParams object
// with the default values initialized.
func NewGetCustomerZoneCostitemsParams() *GetCustomerZoneCostitemsParams {
	var ()
	return &GetCustomerZoneCostitemsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomerZoneCostitemsParamsWithTimeout creates a new GetCustomerZoneCostitemsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCustomerZoneCostitemsParamsWithTimeout(timeout time.Duration) *GetCustomerZoneCostitemsParams {
	var ()
	return &GetCustomerZoneCostitemsParams{

		timeout: timeout,
	}
}

// NewGetCustomerZoneCostitemsParamsWithContext creates a new GetCustomerZoneCostitemsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCustomerZoneCostitemsParamsWithContext(ctx context.Context) *GetCustomerZoneCostitemsParams {
	var ()
	return &GetCustomerZoneCostitemsParams{

		Context: ctx,
	}
}

// NewGetCustomerZoneCostitemsParamsWithHTTPClient creates a new GetCustomerZoneCostitemsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCustomerZoneCostitemsParamsWithHTTPClient(client *http.Client) *GetCustomerZoneCostitemsParams {
	var ()
	return &GetCustomerZoneCostitemsParams{
		HTTPClient: client,
	}
}

/*GetCustomerZoneCostitemsParams contains all the parameters to send to the API endpoint
for the get customer zone costitems operation typically these are written to a http.Request
*/
type GetCustomerZoneCostitemsParams struct {

	/*CustomerID
	  Filter for a specific customer.

	*/
	CustomerID string
	/*End
	  Filter for a specific end time in format YYYY-MM-DDThhmmss.

	*/
	End string
	/*OrderBy
	  Order collection by a specific attribute.

	*/
	OrderBy string
	/*OrderByDirection
	  Direction which the collection should be ordered by. Possible values are: asc (default), desc.

	*/
	OrderByDirection string
	/*Page
	  Pagination page which should be displayed (default: 1)

	*/
	Page string
	/*Rows
	  Number of rows in one pagination page (default: 10)

	*/
	Rows string
	/*Start
	  Filter for a specific start time in format YYYY-MM-DDThhmmss.

	*/
	Start string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) WithTimeout(timeout time.Duration) *GetCustomerZoneCostitemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) WithContext(ctx context.Context) *GetCustomerZoneCostitemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) WithHTTPClient(client *http.Client) *GetCustomerZoneCostitemsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) WithCustomerID(customerID string) *GetCustomerZoneCostitemsParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithEnd adds the end to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) WithEnd(end string) *GetCustomerZoneCostitemsParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) SetEnd(end string) {
	o.End = end
}

// WithOrderBy adds the orderBy to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) WithOrderBy(orderBy string) *GetCustomerZoneCostitemsParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) SetOrderBy(orderBy string) {
	o.OrderBy = orderBy
}

// WithOrderByDirection adds the orderByDirection to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) WithOrderByDirection(orderByDirection string) *GetCustomerZoneCostitemsParams {
	o.SetOrderByDirection(orderByDirection)
	return o
}

// SetOrderByDirection adds the orderByDirection to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) SetOrderByDirection(orderByDirection string) {
	o.OrderByDirection = orderByDirection
}

// WithPage adds the page to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) WithPage(page string) *GetCustomerZoneCostitemsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) SetPage(page string) {
	o.Page = page
}

// WithRows adds the rows to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) WithRows(rows string) *GetCustomerZoneCostitemsParams {
	o.SetRows(rows)
	return o
}

// SetRows adds the rows to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) SetRows(rows string) {
	o.Rows = rows
}

// WithStart adds the start to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) WithStart(start string) *GetCustomerZoneCostitemsParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get customer zone costitems params
func (o *GetCustomerZoneCostitemsParams) SetStart(start string) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomerZoneCostitemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param customer_id
	qrCustomerID := o.CustomerID
	qCustomerID := qrCustomerID
	if qCustomerID != "" {
		if err := r.SetQueryParam("customer_id", qCustomerID); err != nil {
			return err
		}
	}

	// query param end
	qrEnd := o.End
	qEnd := qrEnd
	if qEnd != "" {
		if err := r.SetQueryParam("end", qEnd); err != nil {
			return err
		}
	}

	// query param order_by
	qrOrderBy := o.OrderBy
	qOrderBy := qrOrderBy
	if qOrderBy != "" {
		if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
			return err
		}
	}

	// query param order_by_direction
	qrOrderByDirection := o.OrderByDirection
	qOrderByDirection := qrOrderByDirection
	if qOrderByDirection != "" {
		if err := r.SetQueryParam("order_by_direction", qOrderByDirection); err != nil {
			return err
		}
	}

	// query param page
	qrPage := o.Page
	qPage := qrPage
	if qPage != "" {
		if err := r.SetQueryParam("page", qPage); err != nil {
			return err
		}
	}

	// query param rows
	qrRows := o.Rows
	qRows := qrRows
	if qRows != "" {
		if err := r.SetQueryParam("rows", qRows); err != nil {
			return err
		}
	}

	// query param start
	qrStart := o.Start
	qStart := qrStart
	if qStart != "" {
		if err := r.SetQueryParam("start", qStart); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
