// Code generated by go-swagger; DO NOT EDIT.

package customerzonecosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetaspecificCustomerZoneCostReader is a Reader for the GetaspecificCustomerZoneCost structure.
type GetaspecificCustomerZoneCostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetaspecificCustomerZoneCostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetaspecificCustomerZoneCostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetaspecificCustomerZoneCostOK creates a GetaspecificCustomerZoneCostOK with default headers values
func NewGetaspecificCustomerZoneCostOK() *GetaspecificCustomerZoneCostOK {
	return &GetaspecificCustomerZoneCostOK{}
}

/*GetaspecificCustomerZoneCostOK handles this case with default header values.

GetaspecificCustomerZoneCostOK getaspecific customer zone cost o k
*/
type GetaspecificCustomerZoneCostOK struct {
	Payload string
}

func (o *GetaspecificCustomerZoneCostOK) Error() string {
	return fmt.Sprintf("[GET /customerzonecosts/{id}][%d] getaspecificCustomerZoneCostOK  %+v", 200, o.Payload)
}

func (o *GetaspecificCustomerZoneCostOK) GetPayload() string {
	return o.Payload
}

func (o *GetaspecificCustomerZoneCostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
