// Code generated by go-swagger; DO NOT EDIT.

package ncoslnpcarriers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api1/models"
)

// NewCreateanewNcosLnpCarrierParams creates a new CreateanewNcosLnpCarrierParams object
// with the default values initialized.
func NewCreateanewNcosLnpCarrierParams() *CreateanewNcosLnpCarrierParams {
	var ()
	return &CreateanewNcosLnpCarrierParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateanewNcosLnpCarrierParamsWithTimeout creates a new CreateanewNcosLnpCarrierParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateanewNcosLnpCarrierParamsWithTimeout(timeout time.Duration) *CreateanewNcosLnpCarrierParams {
	var ()
	return &CreateanewNcosLnpCarrierParams{

		timeout: timeout,
	}
}

// NewCreateanewNcosLnpCarrierParamsWithContext creates a new CreateanewNcosLnpCarrierParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateanewNcosLnpCarrierParamsWithContext(ctx context.Context) *CreateanewNcosLnpCarrierParams {
	var ()
	return &CreateanewNcosLnpCarrierParams{

		Context: ctx,
	}
}

// NewCreateanewNcosLnpCarrierParamsWithHTTPClient creates a new CreateanewNcosLnpCarrierParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateanewNcosLnpCarrierParamsWithHTTPClient(client *http.Client) *CreateanewNcosLnpCarrierParams {
	var ()
	return &CreateanewNcosLnpCarrierParams{
		HTTPClient: client,
	}
}

/*CreateanewNcosLnpCarrierParams contains all the parameters to send to the API endpoint
for the createanew ncos lnp carrier operation typically these are written to a http.Request
*/
type CreateanewNcosLnpCarrierParams struct {

	/*Body*/
	Body *models.CreateanewNcosLnpCarrierRequest
	/*ContentType*/
	ContentType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the createanew ncos lnp carrier params
func (o *CreateanewNcosLnpCarrierParams) WithTimeout(timeout time.Duration) *CreateanewNcosLnpCarrierParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the createanew ncos lnp carrier params
func (o *CreateanewNcosLnpCarrierParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the createanew ncos lnp carrier params
func (o *CreateanewNcosLnpCarrierParams) WithContext(ctx context.Context) *CreateanewNcosLnpCarrierParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the createanew ncos lnp carrier params
func (o *CreateanewNcosLnpCarrierParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the createanew ncos lnp carrier params
func (o *CreateanewNcosLnpCarrierParams) WithHTTPClient(client *http.Client) *CreateanewNcosLnpCarrierParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the createanew ncos lnp carrier params
func (o *CreateanewNcosLnpCarrierParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the createanew ncos lnp carrier params
func (o *CreateanewNcosLnpCarrierParams) WithBody(body *models.CreateanewNcosLnpCarrierRequest) *CreateanewNcosLnpCarrierParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the createanew ncos lnp carrier params
func (o *CreateanewNcosLnpCarrierParams) SetBody(body *models.CreateanewNcosLnpCarrierRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the createanew ncos lnp carrier params
func (o *CreateanewNcosLnpCarrierParams) WithContentType(contentType string) *CreateanewNcosLnpCarrierParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the createanew ncos lnp carrier params
func (o *CreateanewNcosLnpCarrierParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WriteToRequest writes these params to a swagger request
func (o *CreateanewNcosLnpCarrierParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
