// Code generated by go-swagger; DO NOT EDIT.

package rewriterulesets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new rewriterulesets API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for rewriterulesets API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	CreateanewRewriteRuleSet(params *CreateanewRewriteRuleSetParams) (*CreateanewRewriteRuleSetCreated, error)

	GetRewriteRuleSetitems(params *GetRewriteRuleSetitemsParams) (*GetRewriteRuleSetitemsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CreateanewRewriteRuleSet creates a new rewrite rule set
*/
func (a *Client) CreateanewRewriteRuleSet(params *CreateanewRewriteRuleSetParams) (*CreateanewRewriteRuleSetCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateanewRewriteRuleSetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "CreateanewRewriteRuleSet",
		Method:             "POST",
		PathPattern:        "/rewriterulesets",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateanewRewriteRuleSetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateanewRewriteRuleSetCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateanewRewriteRuleSet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetRewriteRuleSetitems gets rewrite rule set items
*/
func (a *Client) GetRewriteRuleSetitems(params *GetRewriteRuleSetitemsParams) (*GetRewriteRuleSetitemsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRewriteRuleSetitemsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetRewriteRuleSetitems",
		Method:             "GET",
		PathPattern:        "/rewriterulesets",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRewriteRuleSetitemsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRewriteRuleSetitemsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetRewriteRuleSetitems: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
