// Code generated by go-swagger; DO NOT EDIT.

package subscribers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api/models"
)

// CreateanewSubscriberReader is a Reader for the CreateanewSubscriber structure.
type CreateanewSubscriberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateanewSubscriberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateanewSubscriberCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewCreateanewSubscriberUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateanewSubscriberCreated creates a CreateanewSubscriberCreated with default headers values
func NewCreateanewSubscriberCreated() *CreateanewSubscriberCreated {
	return &CreateanewSubscriberCreated{
		Location: "nostrud velit non",
	}
}

/*CreateanewSubscriberCreated handles this case with default header values.

CreateanewSubscriberCreated createanew subscriber created
*/
type CreateanewSubscriberCreated struct {
	Location string

	Payload []*models.Thenewlycreateditemorempty5
}

func (o *CreateanewSubscriberCreated) Error() string {
	return fmt.Sprintf("[POST /subscribers][%d] createanewSubscriberCreated  %+v", 201, o.Payload)
}

func (o *CreateanewSubscriberCreated) GetPayload() []*models.Thenewlycreateditemorempty5 {
	return o.Payload
}

func (o *CreateanewSubscriberCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Location
	o.Location = response.GetHeader("Location")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateanewSubscriberUnprocessableEntity creates a CreateanewSubscriberUnprocessableEntity with default headers values
func NewCreateanewSubscriberUnprocessableEntity() *CreateanewSubscriberUnprocessableEntity {
	return &CreateanewSubscriberUnprocessableEntity{}
}

/*CreateanewSubscriberUnprocessableEntity handles this case with default header values.

Unprocessable Entity (WebDAV) (RFC 4918)
*/
type CreateanewSubscriberUnprocessableEntity struct {
	Payload *models.Anerror
}

func (o *CreateanewSubscriberUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /subscribers][%d] createanewSubscriberUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateanewSubscriberUnprocessableEntity) GetPayload() *models.Anerror {
	return o.Payload
}

func (o *CreateanewSubscriberUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Anerror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
