// Code generated by go-swagger; DO NOT EDIT.

package trustedsources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api1/models"
)

// CreateanewTrustedSourceReader is a Reader for the CreateanewTrustedSource structure.
type CreateanewTrustedSourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateanewTrustedSourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateanewTrustedSourceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewCreateanewTrustedSourceUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateanewTrustedSourceCreated creates a CreateanewTrustedSourceCreated with default headers values
func NewCreateanewTrustedSourceCreated() *CreateanewTrustedSourceCreated {
	return &CreateanewTrustedSourceCreated{
		Location: "nostrud velit non",
	}
}

/*CreateanewTrustedSourceCreated handles this case with default header values.

CreateanewTrustedSourceCreated createanew trusted source created
*/
type CreateanewTrustedSourceCreated struct {
	Location string

	Payload []*models.Thenewlycreateditemorempty16
}

func (o *CreateanewTrustedSourceCreated) Error() string {
	return fmt.Sprintf("[POST /trustedsources][%d] createanewTrustedSourceCreated  %+v", 201, o.Payload)
}

func (o *CreateanewTrustedSourceCreated) GetPayload() []*models.Thenewlycreateditemorempty16 {
	return o.Payload
}

func (o *CreateanewTrustedSourceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Location
	o.Location = response.GetHeader("Location")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateanewTrustedSourceUnprocessableEntity creates a CreateanewTrustedSourceUnprocessableEntity with default headers values
func NewCreateanewTrustedSourceUnprocessableEntity() *CreateanewTrustedSourceUnprocessableEntity {
	return &CreateanewTrustedSourceUnprocessableEntity{}
}

/*CreateanewTrustedSourceUnprocessableEntity handles this case with default header values.

Unprocessable Entity (WebDAV) (RFC 4918)
*/
type CreateanewTrustedSourceUnprocessableEntity struct {
	Payload *models.Anerror
}

func (o *CreateanewTrustedSourceUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /trustedsources][%d] createanewTrustedSourceUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateanewTrustedSourceUnprocessableEntity) GetPayload() *models.Anerror {
	return o.Payload
}

func (o *CreateanewTrustedSourceUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Anerror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
