// Code generated by go-swagger; DO NOT EDIT.

package trustedsources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTrustedSourceitemsParams creates a new GetTrustedSourceitemsParams object
// with the default values initialized.
func NewGetTrustedSourceitemsParams() *GetTrustedSourceitemsParams {
	var ()
	return &GetTrustedSourceitemsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTrustedSourceitemsParamsWithTimeout creates a new GetTrustedSourceitemsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTrustedSourceitemsParamsWithTimeout(timeout time.Duration) *GetTrustedSourceitemsParams {
	var ()
	return &GetTrustedSourceitemsParams{

		timeout: timeout,
	}
}

// NewGetTrustedSourceitemsParamsWithContext creates a new GetTrustedSourceitemsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTrustedSourceitemsParamsWithContext(ctx context.Context) *GetTrustedSourceitemsParams {
	var ()
	return &GetTrustedSourceitemsParams{

		Context: ctx,
	}
}

// NewGetTrustedSourceitemsParamsWithHTTPClient creates a new GetTrustedSourceitemsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTrustedSourceitemsParamsWithHTTPClient(client *http.Client) *GetTrustedSourceitemsParams {
	var ()
	return &GetTrustedSourceitemsParams{
		HTTPClient: client,
	}
}

/*GetTrustedSourceitemsParams contains all the parameters to send to the API endpoint
for the get trusted sourceitems operation typically these are written to a http.Request
*/
type GetTrustedSourceitemsParams struct {

	/*OrderBy
	  Order collection by a specific attribute.

	*/
	OrderBy string
	/*OrderByDirection
	  Direction which the collection should be ordered by. Possible values are: asc (default), desc.

	*/
	OrderByDirection string
	/*Page
	  Pagination page which should be displayed (default: 1)

	*/
	Page string
	/*Rows
	  Number of rows in one pagination page (default: 10)

	*/
	Rows string
	/*SubscriberID
	  Filter for trusted sources of a specific subscriber

	*/
	SubscriberID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) WithTimeout(timeout time.Duration) *GetTrustedSourceitemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) WithContext(ctx context.Context) *GetTrustedSourceitemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) WithHTTPClient(client *http.Client) *GetTrustedSourceitemsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderBy adds the orderBy to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) WithOrderBy(orderBy string) *GetTrustedSourceitemsParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) SetOrderBy(orderBy string) {
	o.OrderBy = orderBy
}

// WithOrderByDirection adds the orderByDirection to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) WithOrderByDirection(orderByDirection string) *GetTrustedSourceitemsParams {
	o.SetOrderByDirection(orderByDirection)
	return o
}

// SetOrderByDirection adds the orderByDirection to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) SetOrderByDirection(orderByDirection string) {
	o.OrderByDirection = orderByDirection
}

// WithPage adds the page to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) WithPage(page string) *GetTrustedSourceitemsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) SetPage(page string) {
	o.Page = page
}

// WithRows adds the rows to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) WithRows(rows string) *GetTrustedSourceitemsParams {
	o.SetRows(rows)
	return o
}

// SetRows adds the rows to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) SetRows(rows string) {
	o.Rows = rows
}

// WithSubscriberID adds the subscriberID to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) WithSubscriberID(subscriberID string) *GetTrustedSourceitemsParams {
	o.SetSubscriberID(subscriberID)
	return o
}

// SetSubscriberID adds the subscriberId to the get trusted sourceitems params
func (o *GetTrustedSourceitemsParams) SetSubscriberID(subscriberID string) {
	o.SubscriberID = subscriberID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTrustedSourceitemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param order_by
	qrOrderBy := o.OrderBy
	qOrderBy := qrOrderBy
	if qOrderBy != "" {
		if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
			return err
		}
	}

	// query param order_by_direction
	qrOrderByDirection := o.OrderByDirection
	qOrderByDirection := qrOrderByDirection
	if qOrderByDirection != "" {
		if err := r.SetQueryParam("order_by_direction", qOrderByDirection); err != nil {
			return err
		}
	}

	// query param page
	qrPage := o.Page
	qPage := qrPage
	if qPage != "" {
		if err := r.SetQueryParam("page", qPage); err != nil {
			return err
		}
	}

	// query param rows
	qrRows := o.Rows
	qRows := qrRows
	if qRows != "" {
		if err := r.SetQueryParam("rows", qRows); err != nil {
			return err
		}
	}

	// query param subscriber_id
	qrSubscriberID := o.SubscriberID
	qSubscriberID := qrSubscriberID
	if qSubscriberID != "" {
		if err := r.SetQueryParam("subscriber_id", qSubscriberID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
