// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomercontactsByIDGetParams creates a new CustomercontactsByIDGetParams object
// with the default values initialized.
func NewCustomercontactsByIDGetParams() *CustomercontactsByIDGetParams {
	var ()
	return &CustomercontactsByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomercontactsByIDGetParamsWithTimeout creates a new CustomercontactsByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomercontactsByIDGetParamsWithTimeout(timeout time.Duration) *CustomercontactsByIDGetParams {
	var ()
	return &CustomercontactsByIDGetParams{

		timeout: timeout,
	}
}

// NewCustomercontactsByIDGetParamsWithContext creates a new CustomercontactsByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomercontactsByIDGetParamsWithContext(ctx context.Context) *CustomercontactsByIDGetParams {
	var ()
	return &CustomercontactsByIDGetParams{

		Context: ctx,
	}
}

// NewCustomercontactsByIDGetParamsWithHTTPClient creates a new CustomercontactsByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomercontactsByIDGetParamsWithHTTPClient(client *http.Client) *CustomercontactsByIDGetParams {
	var ()
	return &CustomercontactsByIDGetParams{
		HTTPClient: client,
	}
}

/*CustomercontactsByIDGetParams contains all the parameters to send to the API endpoint
for the customercontacts by Id get operation typically these are written to a http.Request
*/
type CustomercontactsByIDGetParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customercontacts by Id get params
func (o *CustomercontactsByIDGetParams) WithTimeout(timeout time.Duration) *CustomercontactsByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customercontacts by Id get params
func (o *CustomercontactsByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customercontacts by Id get params
func (o *CustomercontactsByIDGetParams) WithContext(ctx context.Context) *CustomercontactsByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customercontacts by Id get params
func (o *CustomercontactsByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customercontacts by Id get params
func (o *CustomercontactsByIDGetParams) WithHTTPClient(client *http.Client) *CustomercontactsByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customercontacts by Id get params
func (o *CustomercontactsByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the customercontacts by Id get params
func (o *CustomercontactsByIDGetParams) WithID(id string) *CustomercontactsByIDGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customercontacts by Id get params
func (o *CustomercontactsByIDGetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CustomercontactsByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
