// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomercontactsByIDDeleteParams creates a new CustomercontactsByIDDeleteParams object
// with the default values initialized.
func NewCustomercontactsByIDDeleteParams() *CustomercontactsByIDDeleteParams {
	var ()
	return &CustomercontactsByIDDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomercontactsByIDDeleteParamsWithTimeout creates a new CustomercontactsByIDDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomercontactsByIDDeleteParamsWithTimeout(timeout time.Duration) *CustomercontactsByIDDeleteParams {
	var ()
	return &CustomercontactsByIDDeleteParams{

		timeout: timeout,
	}
}

// NewCustomercontactsByIDDeleteParamsWithContext creates a new CustomercontactsByIDDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomercontactsByIDDeleteParamsWithContext(ctx context.Context) *CustomercontactsByIDDeleteParams {
	var ()
	return &CustomercontactsByIDDeleteParams{

		Context: ctx,
	}
}

// NewCustomercontactsByIDDeleteParamsWithHTTPClient creates a new CustomercontactsByIDDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomercontactsByIDDeleteParamsWithHTTPClient(client *http.Client) *CustomercontactsByIDDeleteParams {
	var ()
	return &CustomercontactsByIDDeleteParams{
		HTTPClient: client,
	}
}

/*CustomercontactsByIDDeleteParams contains all the parameters to send to the API endpoint
for the customercontacts by Id delete operation typically these are written to a http.Request
*/
type CustomercontactsByIDDeleteParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customercontacts by Id delete params
func (o *CustomercontactsByIDDeleteParams) WithTimeout(timeout time.Duration) *CustomercontactsByIDDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customercontacts by Id delete params
func (o *CustomercontactsByIDDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customercontacts by Id delete params
func (o *CustomercontactsByIDDeleteParams) WithContext(ctx context.Context) *CustomercontactsByIDDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customercontacts by Id delete params
func (o *CustomercontactsByIDDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customercontacts by Id delete params
func (o *CustomercontactsByIDDeleteParams) WithHTTPClient(client *http.Client) *CustomercontactsByIDDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customercontacts by Id delete params
func (o *CustomercontactsByIDDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the customercontacts by Id delete params
func (o *CustomercontactsByIDDeleteParams) WithID(id string) *CustomercontactsByIDDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customercontacts by Id delete params
func (o *CustomercontactsByIDDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CustomercontactsByIDDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
