// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmergencymappingsByIDPutParams creates a new EmergencymappingsByIDPutParams object
// with the default values initialized.
func NewEmergencymappingsByIDPutParams() *EmergencymappingsByIDPutParams {
	var ()
	return &EmergencymappingsByIDPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmergencymappingsByIDPutParamsWithTimeout creates a new EmergencymappingsByIDPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmergencymappingsByIDPutParamsWithTimeout(timeout time.Duration) *EmergencymappingsByIDPutParams {
	var ()
	return &EmergencymappingsByIDPutParams{

		timeout: timeout,
	}
}

// NewEmergencymappingsByIDPutParamsWithContext creates a new EmergencymappingsByIDPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmergencymappingsByIDPutParamsWithContext(ctx context.Context) *EmergencymappingsByIDPutParams {
	var ()
	return &EmergencymappingsByIDPutParams{

		Context: ctx,
	}
}

// NewEmergencymappingsByIDPutParamsWithHTTPClient creates a new EmergencymappingsByIDPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmergencymappingsByIDPutParamsWithHTTPClient(client *http.Client) *EmergencymappingsByIDPutParams {
	var ()
	return &EmergencymappingsByIDPutParams{
		HTTPClient: client,
	}
}

/*EmergencymappingsByIDPutParams contains all the parameters to send to the API endpoint
for the emergencymappings by Id put operation typically these are written to a http.Request
*/
type EmergencymappingsByIDPutParams struct {

	/*Body*/
	Body *Replace1changeaspecificEmergencyMappingRequest
	/*ContentType*/
	ContentType string
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) WithTimeout(timeout time.Duration) *EmergencymappingsByIDPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) WithContext(ctx context.Context) *EmergencymappingsByIDPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) WithHTTPClient(client *http.Client) *EmergencymappingsByIDPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) WithBody(body *Replace1changeaspecificEmergencyMappingRequest) *EmergencymappingsByIDPutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) SetBody(body *Replace1changeaspecificEmergencyMappingRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) WithContentType(contentType string) *EmergencymappingsByIDPutParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithID adds the id to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) WithID(id string) *EmergencymappingsByIDPutParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the emergencymappings by Id put params
func (o *EmergencymappingsByIDPutParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EmergencymappingsByIDPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
