// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// LnpcarriersByIDDeleteReader is a Reader for the LnpcarriersByIDDelete structure.
type LnpcarriersByIDDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LnpcarriersByIDDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewLnpcarriersByIDDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLnpcarriersByIDDeleteNoContent creates a LnpcarriersByIDDeleteNoContent with default headers values
func NewLnpcarriersByIDDeleteNoContent() *LnpcarriersByIDDeleteNoContent {
	return &LnpcarriersByIDDeleteNoContent{}
}

/*LnpcarriersByIDDeleteNoContent handles this case with default header values.

LnpcarriersByIDDeleteNoContent lnpcarriers by Id delete no content
*/
type LnpcarriersByIDDeleteNoContent struct {
	Payload interface{}
}

func (o *LnpcarriersByIDDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /lnpcarriers/{id}][%d] lnpcarriersByIdDeleteNoContent  %+v", 204, o.Payload)
}

func (o *LnpcarriersByIDDeleteNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *LnpcarriersByIDDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
