// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NcoslnpcarriersByIDDeleteReader is a Reader for the NcoslnpcarriersByIDDelete structure.
type NcoslnpcarriersByIDDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NcoslnpcarriersByIDDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewNcoslnpcarriersByIDDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNcoslnpcarriersByIDDeleteNoContent creates a NcoslnpcarriersByIDDeleteNoContent with default headers values
func NewNcoslnpcarriersByIDDeleteNoContent() *NcoslnpcarriersByIDDeleteNoContent {
	return &NcoslnpcarriersByIDDeleteNoContent{}
}

/*NcoslnpcarriersByIDDeleteNoContent handles this case with default header values.

NcoslnpcarriersByIDDeleteNoContent ncoslnpcarriers by Id delete no content
*/
type NcoslnpcarriersByIDDeleteNoContent struct {
	Payload interface{}
}

func (o *NcoslnpcarriersByIDDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ncoslnpcarriers/{id}][%d] ncoslnpcarriersByIdDeleteNoContent  %+v", 204, o.Payload)
}

func (o *NcoslnpcarriersByIDDeleteNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *NcoslnpcarriersByIDDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
