// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNcospatternsByIDDeleteParams creates a new NcospatternsByIDDeleteParams object
// with the default values initialized.
func NewNcospatternsByIDDeleteParams() *NcospatternsByIDDeleteParams {
	var ()
	return &NcospatternsByIDDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNcospatternsByIDDeleteParamsWithTimeout creates a new NcospatternsByIDDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNcospatternsByIDDeleteParamsWithTimeout(timeout time.Duration) *NcospatternsByIDDeleteParams {
	var ()
	return &NcospatternsByIDDeleteParams{

		timeout: timeout,
	}
}

// NewNcospatternsByIDDeleteParamsWithContext creates a new NcospatternsByIDDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewNcospatternsByIDDeleteParamsWithContext(ctx context.Context) *NcospatternsByIDDeleteParams {
	var ()
	return &NcospatternsByIDDeleteParams{

		Context: ctx,
	}
}

// NewNcospatternsByIDDeleteParamsWithHTTPClient creates a new NcospatternsByIDDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNcospatternsByIDDeleteParamsWithHTTPClient(client *http.Client) *NcospatternsByIDDeleteParams {
	var ()
	return &NcospatternsByIDDeleteParams{
		HTTPClient: client,
	}
}

/*NcospatternsByIDDeleteParams contains all the parameters to send to the API endpoint
for the ncospatterns by Id delete operation typically these are written to a http.Request
*/
type NcospatternsByIDDeleteParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ncospatterns by Id delete params
func (o *NcospatternsByIDDeleteParams) WithTimeout(timeout time.Duration) *NcospatternsByIDDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ncospatterns by Id delete params
func (o *NcospatternsByIDDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ncospatterns by Id delete params
func (o *NcospatternsByIDDeleteParams) WithContext(ctx context.Context) *NcospatternsByIDDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ncospatterns by Id delete params
func (o *NcospatternsByIDDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ncospatterns by Id delete params
func (o *NcospatternsByIDDeleteParams) WithHTTPClient(client *http.Client) *NcospatternsByIDDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ncospatterns by Id delete params
func (o *NcospatternsByIDDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the ncospatterns by Id delete params
func (o *NcospatternsByIDDeleteParams) WithID(id string) *NcospatternsByIDDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ncospatterns by Id delete params
func (o *NcospatternsByIDDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *NcospatternsByIDDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
