// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPbxdevicemodelsByIDGetParams creates a new PbxdevicemodelsByIDGetParams object
// with the default values initialized.
func NewPbxdevicemodelsByIDGetParams() *PbxdevicemodelsByIDGetParams {
	var ()
	return &PbxdevicemodelsByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPbxdevicemodelsByIDGetParamsWithTimeout creates a new PbxdevicemodelsByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPbxdevicemodelsByIDGetParamsWithTimeout(timeout time.Duration) *PbxdevicemodelsByIDGetParams {
	var ()
	return &PbxdevicemodelsByIDGetParams{

		timeout: timeout,
	}
}

// NewPbxdevicemodelsByIDGetParamsWithContext creates a new PbxdevicemodelsByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewPbxdevicemodelsByIDGetParamsWithContext(ctx context.Context) *PbxdevicemodelsByIDGetParams {
	var ()
	return &PbxdevicemodelsByIDGetParams{

		Context: ctx,
	}
}

// NewPbxdevicemodelsByIDGetParamsWithHTTPClient creates a new PbxdevicemodelsByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPbxdevicemodelsByIDGetParamsWithHTTPClient(client *http.Client) *PbxdevicemodelsByIDGetParams {
	var ()
	return &PbxdevicemodelsByIDGetParams{
		HTTPClient: client,
	}
}

/*PbxdevicemodelsByIDGetParams contains all the parameters to send to the API endpoint
for the pbxdevicemodels by Id get operation typically these are written to a http.Request
*/
type PbxdevicemodelsByIDGetParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the pbxdevicemodels by Id get params
func (o *PbxdevicemodelsByIDGetParams) WithTimeout(timeout time.Duration) *PbxdevicemodelsByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pbxdevicemodels by Id get params
func (o *PbxdevicemodelsByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pbxdevicemodels by Id get params
func (o *PbxdevicemodelsByIDGetParams) WithContext(ctx context.Context) *PbxdevicemodelsByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pbxdevicemodels by Id get params
func (o *PbxdevicemodelsByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pbxdevicemodels by Id get params
func (o *PbxdevicemodelsByIDGetParams) WithHTTPClient(client *http.Client) *PbxdevicemodelsByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pbxdevicemodels by Id get params
func (o *PbxdevicemodelsByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the pbxdevicemodels by Id get params
func (o *PbxdevicemodelsByIDGetParams) WithID(id string) *PbxdevicemodelsByIDGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the pbxdevicemodels by Id get params
func (o *PbxdevicemodelsByIDGetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PbxdevicemodelsByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
