// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/negbie/ngcp-api/models"
)

// PbxdeviceprofilesByIDPutReader is a Reader for the PbxdeviceprofilesByIDPut structure.
type PbxdeviceprofilesByIDPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PbxdeviceprofilesByIDPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPbxdeviceprofilesByIDPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPbxdeviceprofilesByIDPutOK creates a PbxdeviceprofilesByIDPutOK with default headers values
func NewPbxdeviceprofilesByIDPutOK() *PbxdeviceprofilesByIDPutOK {
	return &PbxdeviceprofilesByIDPutOK{}
}

/*PbxdeviceprofilesByIDPutOK handles this case with default header values.

PbxdeviceprofilesByIDPutOK pbxdeviceprofiles by Id put o k
*/
type PbxdeviceprofilesByIDPutOK struct {
	Payload *models.PbxDeviceProfiles
}

func (o *PbxdeviceprofilesByIDPutOK) Error() string {
	return fmt.Sprintf("[PUT /pbxdeviceprofiles/{id}][%d] pbxdeviceprofilesByIdPutOK  %+v", 200, o.Payload)
}

func (o *PbxdeviceprofilesByIDPutOK) GetPayload() *models.PbxDeviceProfiles {
	return o.Payload
}

func (o *PbxdeviceprofilesByIDPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PbxDeviceProfiles)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
