// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPeeringserversByIDGetParams creates a new PeeringserversByIDGetParams object
// with the default values initialized.
func NewPeeringserversByIDGetParams() *PeeringserversByIDGetParams {
	var ()
	return &PeeringserversByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPeeringserversByIDGetParamsWithTimeout creates a new PeeringserversByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPeeringserversByIDGetParamsWithTimeout(timeout time.Duration) *PeeringserversByIDGetParams {
	var ()
	return &PeeringserversByIDGetParams{

		timeout: timeout,
	}
}

// NewPeeringserversByIDGetParamsWithContext creates a new PeeringserversByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewPeeringserversByIDGetParamsWithContext(ctx context.Context) *PeeringserversByIDGetParams {
	var ()
	return &PeeringserversByIDGetParams{

		Context: ctx,
	}
}

// NewPeeringserversByIDGetParamsWithHTTPClient creates a new PeeringserversByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPeeringserversByIDGetParamsWithHTTPClient(client *http.Client) *PeeringserversByIDGetParams {
	var ()
	return &PeeringserversByIDGetParams{
		HTTPClient: client,
	}
}

/*PeeringserversByIDGetParams contains all the parameters to send to the API endpoint
for the peeringservers by Id get operation typically these are written to a http.Request
*/
type PeeringserversByIDGetParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the peeringservers by Id get params
func (o *PeeringserversByIDGetParams) WithTimeout(timeout time.Duration) *PeeringserversByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peeringservers by Id get params
func (o *PeeringserversByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peeringservers by Id get params
func (o *PeeringserversByIDGetParams) WithContext(ctx context.Context) *PeeringserversByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peeringservers by Id get params
func (o *PeeringserversByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peeringservers by Id get params
func (o *PeeringserversByIDGetParams) WithHTTPClient(client *http.Client) *PeeringserversByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peeringservers by Id get params
func (o *PeeringserversByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the peeringservers by Id get params
func (o *PeeringserversByIDGetParams) WithID(id string) *PeeringserversByIDGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the peeringservers by Id get params
func (o *PeeringserversByIDGetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PeeringserversByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
