// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPreferencesmetaentriesByIDPatchParams creates a new PreferencesmetaentriesByIDPatchParams object
// with the default values initialized.
func NewPreferencesmetaentriesByIDPatchParams() *PreferencesmetaentriesByIDPatchParams {
	var ()
	return &PreferencesmetaentriesByIDPatchParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPreferencesmetaentriesByIDPatchParamsWithTimeout creates a new PreferencesmetaentriesByIDPatchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPreferencesmetaentriesByIDPatchParamsWithTimeout(timeout time.Duration) *PreferencesmetaentriesByIDPatchParams {
	var ()
	return &PreferencesmetaentriesByIDPatchParams{

		timeout: timeout,
	}
}

// NewPreferencesmetaentriesByIDPatchParamsWithContext creates a new PreferencesmetaentriesByIDPatchParams object
// with the default values initialized, and the ability to set a context for a request
func NewPreferencesmetaentriesByIDPatchParamsWithContext(ctx context.Context) *PreferencesmetaentriesByIDPatchParams {
	var ()
	return &PreferencesmetaentriesByIDPatchParams{

		Context: ctx,
	}
}

// NewPreferencesmetaentriesByIDPatchParamsWithHTTPClient creates a new PreferencesmetaentriesByIDPatchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPreferencesmetaentriesByIDPatchParamsWithHTTPClient(client *http.Client) *PreferencesmetaentriesByIDPatchParams {
	var ()
	return &PreferencesmetaentriesByIDPatchParams{
		HTTPClient: client,
	}
}

/*PreferencesmetaentriesByIDPatchParams contains all the parameters to send to the API endpoint
for the preferencesmetaentries by Id patch operation typically these are written to a http.Request
*/
type PreferencesmetaentriesByIDPatchParams struct {

	/*Body*/
	Body string
	/*ContentType*/
	ContentType string
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) WithTimeout(timeout time.Duration) *PreferencesmetaentriesByIDPatchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) WithContext(ctx context.Context) *PreferencesmetaentriesByIDPatchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) WithHTTPClient(client *http.Client) *PreferencesmetaentriesByIDPatchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) WithBody(body string) *PreferencesmetaentriesByIDPatchParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) SetBody(body string) {
	o.Body = body
}

// WithContentType adds the contentType to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) WithContentType(contentType string) *PreferencesmetaentriesByIDPatchParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithID adds the id to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) WithID(id string) *PreferencesmetaentriesByIDPatchParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the preferencesmetaentries by Id patch params
func (o *PreferencesmetaentriesByIDPatchParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PreferencesmetaentriesByIDPatchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
