// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ResellersByIDPatchReader is a Reader for the ResellersByIDPatch structure.
type ResellersByIDPatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResellersByIDPatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewResellersByIDPatchNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewResellersByIDPatchNoContent creates a ResellersByIDPatchNoContent with default headers values
func NewResellersByIDPatchNoContent() *ResellersByIDPatchNoContent {
	return &ResellersByIDPatchNoContent{}
}

/*ResellersByIDPatchNoContent handles this case with default header values.

ResellersByIDPatchNoContent resellers by Id patch no content
*/
type ResellersByIDPatchNoContent struct {
	Payload interface{}
}

func (o *ResellersByIDPatchNoContent) Error() string {
	return fmt.Sprintf("[PATCH /resellers/{id}][%d] resellersByIdPatchNoContent  %+v", 204, o.Payload)
}

func (o *ResellersByIDPatchNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *ResellersByIDPatchNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
