// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSpeeddialsByIDPutParams creates a new SpeeddialsByIDPutParams object
// with the default values initialized.
func NewSpeeddialsByIDPutParams() *SpeeddialsByIDPutParams {
	var ()
	return &SpeeddialsByIDPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSpeeddialsByIDPutParamsWithTimeout creates a new SpeeddialsByIDPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSpeeddialsByIDPutParamsWithTimeout(timeout time.Duration) *SpeeddialsByIDPutParams {
	var ()
	return &SpeeddialsByIDPutParams{

		timeout: timeout,
	}
}

// NewSpeeddialsByIDPutParamsWithContext creates a new SpeeddialsByIDPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewSpeeddialsByIDPutParamsWithContext(ctx context.Context) *SpeeddialsByIDPutParams {
	var ()
	return &SpeeddialsByIDPutParams{

		Context: ctx,
	}
}

// NewSpeeddialsByIDPutParamsWithHTTPClient creates a new SpeeddialsByIDPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSpeeddialsByIDPutParamsWithHTTPClient(client *http.Client) *SpeeddialsByIDPutParams {
	var ()
	return &SpeeddialsByIDPutParams{
		HTTPClient: client,
	}
}

/*SpeeddialsByIDPutParams contains all the parameters to send to the API endpoint
for the speeddials by Id put operation typically these are written to a http.Request
*/
type SpeeddialsByIDPutParams struct {

	/*Body*/
	Body *Replace1changeaspecificSpeedDialRequest
	/*ContentType*/
	ContentType string
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) WithTimeout(timeout time.Duration) *SpeeddialsByIDPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) WithContext(ctx context.Context) *SpeeddialsByIDPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) WithHTTPClient(client *http.Client) *SpeeddialsByIDPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) WithBody(body *Replace1changeaspecificSpeedDialRequest) *SpeeddialsByIDPutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) SetBody(body *Replace1changeaspecificSpeedDialRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) WithContentType(contentType string) *SpeeddialsByIDPutParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithID adds the id to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) WithID(id string) *SpeeddialsByIDPutParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the speeddials by Id put params
func (o *SpeeddialsByIDPutParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SpeeddialsByIDPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
