// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SubscriberpreferencesByIDPutReader is a Reader for the SubscriberpreferencesByIDPut structure.
type SubscriberpreferencesByIDPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SubscriberpreferencesByIDPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSubscriberpreferencesByIDPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSubscriberpreferencesByIDPutOK creates a SubscriberpreferencesByIDPutOK with default headers values
func NewSubscriberpreferencesByIDPutOK() *SubscriberpreferencesByIDPutOK {
	return &SubscriberpreferencesByIDPutOK{}
}

/*SubscriberpreferencesByIDPutOK handles this case with default header values.

SubscriberpreferencesByIDPutOK subscriberpreferences by Id put o k
*/
type SubscriberpreferencesByIDPutOK struct {
	Payload string
}

func (o *SubscriberpreferencesByIDPutOK) Error() string {
	return fmt.Sprintf("[PUT /subscriberpreferences/{id}][%d] subscriberpreferencesByIdPutOK  %+v", 200, o.Payload)
}

func (o *SubscriberpreferencesByIDPutOK) GetPayload() string {
	return o.Payload
}

func (o *SubscriberpreferencesByIDPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
