// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSystemcontactsByIDPutParams creates a new SystemcontactsByIDPutParams object
// with the default values initialized.
func NewSystemcontactsByIDPutParams() *SystemcontactsByIDPutParams {
	var ()
	return &SystemcontactsByIDPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSystemcontactsByIDPutParamsWithTimeout creates a new SystemcontactsByIDPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSystemcontactsByIDPutParamsWithTimeout(timeout time.Duration) *SystemcontactsByIDPutParams {
	var ()
	return &SystemcontactsByIDPutParams{

		timeout: timeout,
	}
}

// NewSystemcontactsByIDPutParamsWithContext creates a new SystemcontactsByIDPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewSystemcontactsByIDPutParamsWithContext(ctx context.Context) *SystemcontactsByIDPutParams {
	var ()
	return &SystemcontactsByIDPutParams{

		Context: ctx,
	}
}

// NewSystemcontactsByIDPutParamsWithHTTPClient creates a new SystemcontactsByIDPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSystemcontactsByIDPutParamsWithHTTPClient(client *http.Client) *SystemcontactsByIDPutParams {
	var ()
	return &SystemcontactsByIDPutParams{
		HTTPClient: client,
	}
}

/*SystemcontactsByIDPutParams contains all the parameters to send to the API endpoint
for the systemcontacts by Id put operation typically these are written to a http.Request
*/
type SystemcontactsByIDPutParams struct {

	/*Body*/
	Body *Replace1changeaspecificSystemContactRequest
	/*ContentType*/
	ContentType string
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) WithTimeout(timeout time.Duration) *SystemcontactsByIDPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) WithContext(ctx context.Context) *SystemcontactsByIDPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) WithHTTPClient(client *http.Client) *SystemcontactsByIDPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) WithBody(body *Replace1changeaspecificSystemContactRequest) *SystemcontactsByIDPutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) SetBody(body *Replace1changeaspecificSystemContactRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) WithContentType(contentType string) *SystemcontactsByIDPutParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithID adds the id to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) WithID(id string) *SystemcontactsByIDPutParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the systemcontacts by Id put params
func (o *SystemcontactsByIDPutParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SystemcontactsByIDPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
