// Code generated by go-swagger; DO NOT EDIT.

package id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpnrewritesetsByIDDeleteReader is a Reader for the UpnrewritesetsByIDDelete structure.
type UpnrewritesetsByIDDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpnrewritesetsByIDDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpnrewritesetsByIDDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpnrewritesetsByIDDeleteNoContent creates a UpnrewritesetsByIDDeleteNoContent with default headers values
func NewUpnrewritesetsByIDDeleteNoContent() *UpnrewritesetsByIDDeleteNoContent {
	return &UpnrewritesetsByIDDeleteNoContent{}
}

/*UpnrewritesetsByIDDeleteNoContent handles this case with default header values.

UpnrewritesetsByIDDeleteNoContent upnrewritesets by Id delete no content
*/
type UpnrewritesetsByIDDeleteNoContent struct {
	Payload interface{}
}

func (o *UpnrewritesetsByIDDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /upnrewritesets/{id}][%d] upnrewritesetsByIdDeleteNoContent  %+v", 204, o.Payload)
}

func (o *UpnrewritesetsByIDDeleteNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *UpnrewritesetsByIDDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
