// Code generated by go-swagger; DO NOT EDIT.

package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetaspecificFaxRecordingReader is a Reader for the GetaspecificFaxRecording structure.
type GetaspecificFaxRecordingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetaspecificFaxRecordingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetaspecificFaxRecordingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetaspecificFaxRecordingOK creates a GetaspecificFaxRecordingOK with default headers values
func NewGetaspecificFaxRecordingOK() *GetaspecificFaxRecordingOK {
	return &GetaspecificFaxRecordingOK{}
}

/*GetaspecificFaxRecordingOK handles this case with default header values.

GetaspecificFaxRecordingOK getaspecific fax recording o k
*/
type GetaspecificFaxRecordingOK struct {
	Payload string
}

func (o *GetaspecificFaxRecordingOK) Error() string {
	return fmt.Sprintf("[GET /faxrecordings/{id}][%d] getaspecificFaxRecordingOK  %+v", 200, o.Payload)
}

func (o *GetaspecificFaxRecordingOK) GetPayload() string {
	return o.Payload
}

func (o *GetaspecificFaxRecordingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
