/*
 * NGCP API
 *
 * Sipwise NGCP API (role admin)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CustomerBalance struct for CustomerBalance
type CustomerBalance struct {
	// The current cash balance of the customer in EUR/USD/etc.
	CashBalance float32 `json:"cash_balance,omitempty"`
	// The free-time spent during the current interval in seconds (read-only).
	FreeTimeSpent float32 `json:"free_time_spent"`
	// The amount spent during the current interval in EUR/USD/etc (read-only).
	CashDebit float32 `json:"cash_debit"`
	// The current free-time balance of the customer in seconds.
	FreeTimeBalance float32 `json:"free_time_balance,omitempty"`
	// The ratio to reduce free cash/time in the initial balance period (month), when the customer was created. Readonly.
	Ratio float32 `json:"ratio"`
}
