/*
 * NGCP API
 *
 * Sipwise NGCP API (role admin)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TopupVoucher struct for TopupVoucher
type TopupVoucher struct {
	// An external ID to identify the top-up request in the top-up log.
	RequestToken string `json:"request_token"`
	// The voucher code for the topup.
	Code string `json:"code,omitempty"`
	// The subscriber for which to topup the balance.
	SubscriberId float32 `json:"subscriber_id,omitempty"`
}
