/*
 * NGCP API
 *
 * Sipwise NGCP API (role admin)
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CfbNumberSet struct for CfbNumberSet
type CfbNumberSet struct {
	// The name of the bnumber set
	Name string `json:"name,omitempty"`
	// The bnumber set mode. A blacklist matches everything except numbers in the list, a whitelist only matches numbers (or expressions) in this list.
	Mode string `json:"mode,omitempty"`
	// An array of bnumbers, each containing the key \"bnumber\" which will be matched against the called party number (callee) to determine whether to apply the callforward or not. \"bnumber\" is the callee's number in E164 format to match. They are formatted either as regular expressions or shell patterns depending on the value of the is_regex flag.
	Bnumbers []CfbNumberSetBnumbers `json:"bnumbers"`
	// A flag indicating, whether the numbers in this set are regular expressions. If true, all bnumbers will be interepreted as perl compatible regular expressions and matched against the B-Number of the calls. If false, shell pattern the whole numbers are matched while shell patterns like 431* or 49123[1-5]67 are possible. If true, capturing groups can be formed using parentheses and referenced in the destinations via \\\\1, \\\\2,... .
	IsRegex bool `json:"is_regex"`
	// The subscriber id this b-number set belongs to
	SubscriberId float32 `json:"subscriber_id,omitempty"`
}
