// Code generated by go-swagger; DO NOT EDIT.

package phonebookentries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPhonebookEntryitemsParams creates a new GetPhonebookEntryitemsParams object
// with the default values initialized.
func NewGetPhonebookEntryitemsParams() *GetPhonebookEntryitemsParams {
	var ()
	return &GetPhonebookEntryitemsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPhonebookEntryitemsParamsWithTimeout creates a new GetPhonebookEntryitemsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPhonebookEntryitemsParamsWithTimeout(timeout time.Duration) *GetPhonebookEntryitemsParams {
	var ()
	return &GetPhonebookEntryitemsParams{

		timeout: timeout,
	}
}

// NewGetPhonebookEntryitemsParamsWithContext creates a new GetPhonebookEntryitemsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPhonebookEntryitemsParamsWithContext(ctx context.Context) *GetPhonebookEntryitemsParams {
	var ()
	return &GetPhonebookEntryitemsParams{

		Context: ctx,
	}
}

// NewGetPhonebookEntryitemsParamsWithHTTPClient creates a new GetPhonebookEntryitemsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPhonebookEntryitemsParamsWithHTTPClient(client *http.Client) *GetPhonebookEntryitemsParams {
	var ()
	return &GetPhonebookEntryitemsParams{
		HTTPClient: client,
	}
}

/*GetPhonebookEntryitemsParams contains all the parameters to send to the API endpoint
for the get phonebook entryitems operation typically these are written to a http.Request
*/
type GetPhonebookEntryitemsParams struct {

	/*CustomerID
	  Filter for Phonebook entries belonging to a specific contract

	*/
	CustomerID string
	/*Name
	  Filter for Phonebook numbers with a specific name (wildcards possible)

	*/
	Name string
	/*Number
	  Filter for Phonebook numbers with a specific number (wildcards possible)

	*/
	Number string
	/*OrderBy
	  Order collection by a specific attribute.

	*/
	OrderBy string
	/*OrderByDirection
	  Direction which the collection should be ordered by. Possible values are: asc (default), desc.

	*/
	OrderByDirection string
	/*Page
	  Pagination page which should be displayed (default: 1)

	*/
	Page string
	/*ResellerID
	  Filter for Phonebook entries belonging to a specific reseeller

	*/
	ResellerID string
	/*Rows
	  Number of rows in one pagination page (default: 10)

	*/
	Rows string
	/*SubscriberID
	  Filter for Phonebook entries belonging to a specific subscriber

	*/
	SubscriberID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithTimeout(timeout time.Duration) *GetPhonebookEntryitemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithContext(ctx context.Context) *GetPhonebookEntryitemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithHTTPClient(client *http.Client) *GetPhonebookEntryitemsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithCustomerID(customerID string) *GetPhonebookEntryitemsParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithName adds the name to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithName(name string) *GetPhonebookEntryitemsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetName(name string) {
	o.Name = name
}

// WithNumber adds the number to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithNumber(number string) *GetPhonebookEntryitemsParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetNumber(number string) {
	o.Number = number
}

// WithOrderBy adds the orderBy to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithOrderBy(orderBy string) *GetPhonebookEntryitemsParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetOrderBy(orderBy string) {
	o.OrderBy = orderBy
}

// WithOrderByDirection adds the orderByDirection to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithOrderByDirection(orderByDirection string) *GetPhonebookEntryitemsParams {
	o.SetOrderByDirection(orderByDirection)
	return o
}

// SetOrderByDirection adds the orderByDirection to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetOrderByDirection(orderByDirection string) {
	o.OrderByDirection = orderByDirection
}

// WithPage adds the page to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithPage(page string) *GetPhonebookEntryitemsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetPage(page string) {
	o.Page = page
}

// WithResellerID adds the resellerID to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithResellerID(resellerID string) *GetPhonebookEntryitemsParams {
	o.SetResellerID(resellerID)
	return o
}

// SetResellerID adds the resellerId to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetResellerID(resellerID string) {
	o.ResellerID = resellerID
}

// WithRows adds the rows to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithRows(rows string) *GetPhonebookEntryitemsParams {
	o.SetRows(rows)
	return o
}

// SetRows adds the rows to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetRows(rows string) {
	o.Rows = rows
}

// WithSubscriberID adds the subscriberID to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) WithSubscriberID(subscriberID string) *GetPhonebookEntryitemsParams {
	o.SetSubscriberID(subscriberID)
	return o
}

// SetSubscriberID adds the subscriberId to the get phonebook entryitems params
func (o *GetPhonebookEntryitemsParams) SetSubscriberID(subscriberID string) {
	o.SubscriberID = subscriberID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPhonebookEntryitemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param customer_id
	qrCustomerID := o.CustomerID
	qCustomerID := qrCustomerID
	if qCustomerID != "" {
		if err := r.SetQueryParam("customer_id", qCustomerID); err != nil {
			return err
		}
	}

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {
		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	// query param number
	qrNumber := o.Number
	qNumber := qrNumber
	if qNumber != "" {
		if err := r.SetQueryParam("number", qNumber); err != nil {
			return err
		}
	}

	// query param order_by
	qrOrderBy := o.OrderBy
	qOrderBy := qrOrderBy
	if qOrderBy != "" {
		if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
			return err
		}
	}

	// query param order_by_direction
	qrOrderByDirection := o.OrderByDirection
	qOrderByDirection := qrOrderByDirection
	if qOrderByDirection != "" {
		if err := r.SetQueryParam("order_by_direction", qOrderByDirection); err != nil {
			return err
		}
	}

	// query param page
	qrPage := o.Page
	qPage := qrPage
	if qPage != "" {
		if err := r.SetQueryParam("page", qPage); err != nil {
			return err
		}
	}

	// query param reseller_id
	qrResellerID := o.ResellerID
	qResellerID := qrResellerID
	if qResellerID != "" {
		if err := r.SetQueryParam("reseller_id", qResellerID); err != nil {
			return err
		}
	}

	// query param rows
	qrRows := o.Rows
	qRows := qrRows
	if qRows != "" {
		if err := r.SetQueryParam("rows", qRows); err != nil {
			return err
		}
	}

	// query param subscriber_id
	qrSubscriberID := o.SubscriberID
	qSubscriberID := qrSubscriberID
	if qSubscriberID != "" {
		if err := r.SetQueryParam("subscriber_id", qSubscriberID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
