// Code generated by go-swagger; DO NOT EDIT.

package lnpcarriers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api/models"
)

// GetLnpCarrieritemsReader is a Reader for the GetLnpCarrieritems structure.
type GetLnpCarrieritemsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLnpCarrieritemsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLnpCarrieritemsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLnpCarrieritemsOK creates a GetLnpCarrieritemsOK with default headers values
func NewGetLnpCarrieritemsOK() *GetLnpCarrieritemsOK {
	return &GetLnpCarrieritemsOK{}
}

/*GetLnpCarrieritemsOK handles this case with default header values.

GetLnpCarrieritemsOK get lnp carrieritems o k
*/
type GetLnpCarrieritemsOK struct {
	Payload []*models.LnpCarriers
}

func (o *GetLnpCarrieritemsOK) Error() string {
	return fmt.Sprintf("[GET /lnpcarriers][%d] getLnpCarrieritemsOK  %+v", 200, o.Payload)
}

func (o *GetLnpCarrieritemsOK) GetPayload() []*models.LnpCarriers {
	return o.Payload
}

func (o *GetLnpCarrieritemsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
