// Code generated by go-swagger; DO NOT EDIT.

package soundhandles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/negbie/ngcp-api/models"
)

// SoundhandlesGetReader is a Reader for the SoundhandlesGet structure.
type SoundhandlesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SoundhandlesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSoundhandlesGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSoundhandlesGetOK creates a SoundhandlesGetOK with default headers values
func NewSoundhandlesGetOK() *SoundhandlesGetOK {
	return &SoundhandlesGetOK{}
}

/*SoundhandlesGetOK handles this case with default header values.

SoundhandlesGetOK soundhandles get o k
*/
type SoundhandlesGetOK struct {
	Payload []*models.SoundHandle
}

func (o *SoundhandlesGetOK) Error() string {
	return fmt.Sprintf("[GET /soundhandles][%d] soundhandlesGetOK  %+v", 200, o.Payload)
}

func (o *SoundhandlesGetOK) GetPayload() []*models.SoundHandle {
	return o.Payload
}

func (o *SoundhandlesGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
