// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewChangeaspecificMailToFaxSettingParams creates a new ChangeaspecificMailToFaxSettingParams object
// with the default values initialized.
func NewChangeaspecificMailToFaxSettingParams() *ChangeaspecificMailToFaxSettingParams {
	var ()
	return &ChangeaspecificMailToFaxSettingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeaspecificMailToFaxSettingParamsWithTimeout creates a new ChangeaspecificMailToFaxSettingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeaspecificMailToFaxSettingParamsWithTimeout(timeout time.Duration) *ChangeaspecificMailToFaxSettingParams {
	var ()
	return &ChangeaspecificMailToFaxSettingParams{

		timeout: timeout,
	}
}

// NewChangeaspecificMailToFaxSettingParamsWithContext creates a new ChangeaspecificMailToFaxSettingParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeaspecificMailToFaxSettingParamsWithContext(ctx context.Context) *ChangeaspecificMailToFaxSettingParams {
	var ()
	return &ChangeaspecificMailToFaxSettingParams{

		Context: ctx,
	}
}

// NewChangeaspecificMailToFaxSettingParamsWithHTTPClient creates a new ChangeaspecificMailToFaxSettingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeaspecificMailToFaxSettingParamsWithHTTPClient(client *http.Client) *ChangeaspecificMailToFaxSettingParams {
	var ()
	return &ChangeaspecificMailToFaxSettingParams{
		HTTPClient: client,
	}
}

/*ChangeaspecificMailToFaxSettingParams contains all the parameters to send to the API endpoint
for the changeaspecific mail to fax setting operation typically these are written to a http.Request
*/
type ChangeaspecificMailToFaxSettingParams struct {

	/*Body*/
	Body string
	/*ContentType*/
	ContentType string
	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) WithTimeout(timeout time.Duration) *ChangeaspecificMailToFaxSettingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) WithContext(ctx context.Context) *ChangeaspecificMailToFaxSettingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) WithHTTPClient(client *http.Client) *ChangeaspecificMailToFaxSettingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) WithBody(body string) *ChangeaspecificMailToFaxSettingParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) SetBody(body string) {
	o.Body = body
}

// WithContentType adds the contentType to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) WithContentType(contentType string) *ChangeaspecificMailToFaxSettingParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithID adds the id to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) WithID(id string) *ChangeaspecificMailToFaxSettingParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the changeaspecific mail to fax setting params
func (o *ChangeaspecificMailToFaxSettingParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeaspecificMailToFaxSettingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
