// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewChangeaspecificPeeringInboundRuleParams creates a new ChangeaspecificPeeringInboundRuleParams object
// with the default values initialized.
func NewChangeaspecificPeeringInboundRuleParams() *ChangeaspecificPeeringInboundRuleParams {
	var ()
	return &ChangeaspecificPeeringInboundRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeaspecificPeeringInboundRuleParamsWithTimeout creates a new ChangeaspecificPeeringInboundRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeaspecificPeeringInboundRuleParamsWithTimeout(timeout time.Duration) *ChangeaspecificPeeringInboundRuleParams {
	var ()
	return &ChangeaspecificPeeringInboundRuleParams{

		timeout: timeout,
	}
}

// NewChangeaspecificPeeringInboundRuleParamsWithContext creates a new ChangeaspecificPeeringInboundRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeaspecificPeeringInboundRuleParamsWithContext(ctx context.Context) *ChangeaspecificPeeringInboundRuleParams {
	var ()
	return &ChangeaspecificPeeringInboundRuleParams{

		Context: ctx,
	}
}

// NewChangeaspecificPeeringInboundRuleParamsWithHTTPClient creates a new ChangeaspecificPeeringInboundRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeaspecificPeeringInboundRuleParamsWithHTTPClient(client *http.Client) *ChangeaspecificPeeringInboundRuleParams {
	var ()
	return &ChangeaspecificPeeringInboundRuleParams{
		HTTPClient: client,
	}
}

/*ChangeaspecificPeeringInboundRuleParams contains all the parameters to send to the API endpoint
for the changeaspecific peering inbound rule operation typically these are written to a http.Request
*/
type ChangeaspecificPeeringInboundRuleParams struct {

	/*Body*/
	Body string
	/*ContentType*/
	ContentType string
	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) WithTimeout(timeout time.Duration) *ChangeaspecificPeeringInboundRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) WithContext(ctx context.Context) *ChangeaspecificPeeringInboundRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) WithHTTPClient(client *http.Client) *ChangeaspecificPeeringInboundRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) WithBody(body string) *ChangeaspecificPeeringInboundRuleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) SetBody(body string) {
	o.Body = body
}

// WithContentType adds the contentType to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) WithContentType(contentType string) *ChangeaspecificPeeringInboundRuleParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithID adds the id to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) WithID(id string) *ChangeaspecificPeeringInboundRuleParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the changeaspecific peering inbound rule params
func (o *ChangeaspecificPeeringInboundRuleParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeaspecificPeeringInboundRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
