// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteaspecificSystemContactParams creates a new DeleteaspecificSystemContactParams object
// with the default values initialized.
func NewDeleteaspecificSystemContactParams() *DeleteaspecificSystemContactParams {
	var ()
	return &DeleteaspecificSystemContactParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteaspecificSystemContactParamsWithTimeout creates a new DeleteaspecificSystemContactParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteaspecificSystemContactParamsWithTimeout(timeout time.Duration) *DeleteaspecificSystemContactParams {
	var ()
	return &DeleteaspecificSystemContactParams{

		timeout: timeout,
	}
}

// NewDeleteaspecificSystemContactParamsWithContext creates a new DeleteaspecificSystemContactParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteaspecificSystemContactParamsWithContext(ctx context.Context) *DeleteaspecificSystemContactParams {
	var ()
	return &DeleteaspecificSystemContactParams{

		Context: ctx,
	}
}

// NewDeleteaspecificSystemContactParamsWithHTTPClient creates a new DeleteaspecificSystemContactParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteaspecificSystemContactParamsWithHTTPClient(client *http.Client) *DeleteaspecificSystemContactParams {
	var ()
	return &DeleteaspecificSystemContactParams{
		HTTPClient: client,
	}
}

/*DeleteaspecificSystemContactParams contains all the parameters to send to the API endpoint
for the deleteaspecific system contact operation typically these are written to a http.Request
*/
type DeleteaspecificSystemContactParams struct {

	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the deleteaspecific system contact params
func (o *DeleteaspecificSystemContactParams) WithTimeout(timeout time.Duration) *DeleteaspecificSystemContactParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the deleteaspecific system contact params
func (o *DeleteaspecificSystemContactParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the deleteaspecific system contact params
func (o *DeleteaspecificSystemContactParams) WithContext(ctx context.Context) *DeleteaspecificSystemContactParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the deleteaspecific system contact params
func (o *DeleteaspecificSystemContactParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the deleteaspecific system contact params
func (o *DeleteaspecificSystemContactParams) WithHTTPClient(client *http.Client) *DeleteaspecificSystemContactParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the deleteaspecific system contact params
func (o *DeleteaspecificSystemContactParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the deleteaspecific system contact params
func (o *DeleteaspecificSystemContactParams) WithID(id string) *DeleteaspecificSystemContactParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the deleteaspecific system contact params
func (o *DeleteaspecificSystemContactParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteaspecificSystemContactParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
