// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteaspecificCCMapEntryParams creates a new DeleteaspecificCCMapEntryParams object
// with the default values initialized.
func NewDeleteaspecificCCMapEntryParams() *DeleteaspecificCCMapEntryParams {
	var ()
	return &DeleteaspecificCCMapEntryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteaspecificCCMapEntryParamsWithTimeout creates a new DeleteaspecificCCMapEntryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteaspecificCCMapEntryParamsWithTimeout(timeout time.Duration) *DeleteaspecificCCMapEntryParams {
	var ()
	return &DeleteaspecificCCMapEntryParams{

		timeout: timeout,
	}
}

// NewDeleteaspecificCCMapEntryParamsWithContext creates a new DeleteaspecificCCMapEntryParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteaspecificCCMapEntryParamsWithContext(ctx context.Context) *DeleteaspecificCCMapEntryParams {
	var ()
	return &DeleteaspecificCCMapEntryParams{

		Context: ctx,
	}
}

// NewDeleteaspecificCCMapEntryParamsWithHTTPClient creates a new DeleteaspecificCCMapEntryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteaspecificCCMapEntryParamsWithHTTPClient(client *http.Client) *DeleteaspecificCCMapEntryParams {
	var ()
	return &DeleteaspecificCCMapEntryParams{
		HTTPClient: client,
	}
}

/*DeleteaspecificCCMapEntryParams contains all the parameters to send to the API endpoint
for the deleteaspecific c c map entry operation typically these are written to a http.Request
*/
type DeleteaspecificCCMapEntryParams struct {

	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the deleteaspecific c c map entry params
func (o *DeleteaspecificCCMapEntryParams) WithTimeout(timeout time.Duration) *DeleteaspecificCCMapEntryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the deleteaspecific c c map entry params
func (o *DeleteaspecificCCMapEntryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the deleteaspecific c c map entry params
func (o *DeleteaspecificCCMapEntryParams) WithContext(ctx context.Context) *DeleteaspecificCCMapEntryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the deleteaspecific c c map entry params
func (o *DeleteaspecificCCMapEntryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the deleteaspecific c c map entry params
func (o *DeleteaspecificCCMapEntryParams) WithHTTPClient(client *http.Client) *DeleteaspecificCCMapEntryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the deleteaspecific c c map entry params
func (o *DeleteaspecificCCMapEntryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the deleteaspecific c c map entry params
func (o *DeleteaspecificCCMapEntryParams) WithID(id string) *DeleteaspecificCCMapEntryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the deleteaspecific c c map entry params
func (o *DeleteaspecificCCMapEntryParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteaspecificCCMapEntryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
