// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteaspecificSystemContactReader is a Reader for the DeleteaspecificSystemContact structure.
type DeleteaspecificSystemContactReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteaspecificSystemContactReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteaspecificSystemContactNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteaspecificSystemContactNoContent creates a DeleteaspecificSystemContactNoContent with default headers values
func NewDeleteaspecificSystemContactNoContent() *DeleteaspecificSystemContactNoContent {
	return &DeleteaspecificSystemContactNoContent{}
}

/*DeleteaspecificSystemContactNoContent handles this case with default header values.

DeleteaspecificSystemContactNoContent deleteaspecific system contact no content
*/
type DeleteaspecificSystemContactNoContent struct {
	Payload interface{}
}

func (o *DeleteaspecificSystemContactNoContent) Error() string {
	return fmt.Sprintf("[DELETE /systemcontacts/{id}][%d] deleteaspecificSystemContactNoContent  %+v", 204, o.Payload)
}

func (o *DeleteaspecificSystemContactNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteaspecificSystemContactNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
