// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteaspecificSubscriberRegistrationParams creates a new DeleteaspecificSubscriberRegistrationParams object
// with the default values initialized.
func NewDeleteaspecificSubscriberRegistrationParams() *DeleteaspecificSubscriberRegistrationParams {
	var ()
	return &DeleteaspecificSubscriberRegistrationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteaspecificSubscriberRegistrationParamsWithTimeout creates a new DeleteaspecificSubscriberRegistrationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteaspecificSubscriberRegistrationParamsWithTimeout(timeout time.Duration) *DeleteaspecificSubscriberRegistrationParams {
	var ()
	return &DeleteaspecificSubscriberRegistrationParams{

		timeout: timeout,
	}
}

// NewDeleteaspecificSubscriberRegistrationParamsWithContext creates a new DeleteaspecificSubscriberRegistrationParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteaspecificSubscriberRegistrationParamsWithContext(ctx context.Context) *DeleteaspecificSubscriberRegistrationParams {
	var ()
	return &DeleteaspecificSubscriberRegistrationParams{

		Context: ctx,
	}
}

// NewDeleteaspecificSubscriberRegistrationParamsWithHTTPClient creates a new DeleteaspecificSubscriberRegistrationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteaspecificSubscriberRegistrationParamsWithHTTPClient(client *http.Client) *DeleteaspecificSubscriberRegistrationParams {
	var ()
	return &DeleteaspecificSubscriberRegistrationParams{
		HTTPClient: client,
	}
}

/*DeleteaspecificSubscriberRegistrationParams contains all the parameters to send to the API endpoint
for the deleteaspecific subscriber registration operation typically these are written to a http.Request
*/
type DeleteaspecificSubscriberRegistrationParams struct {

	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the deleteaspecific subscriber registration params
func (o *DeleteaspecificSubscriberRegistrationParams) WithTimeout(timeout time.Duration) *DeleteaspecificSubscriberRegistrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the deleteaspecific subscriber registration params
func (o *DeleteaspecificSubscriberRegistrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the deleteaspecific subscriber registration params
func (o *DeleteaspecificSubscriberRegistrationParams) WithContext(ctx context.Context) *DeleteaspecificSubscriberRegistrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the deleteaspecific subscriber registration params
func (o *DeleteaspecificSubscriberRegistrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the deleteaspecific subscriber registration params
func (o *DeleteaspecificSubscriberRegistrationParams) WithHTTPClient(client *http.Client) *DeleteaspecificSubscriberRegistrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the deleteaspecific subscriber registration params
func (o *DeleteaspecificSubscriberRegistrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the deleteaspecific subscriber registration params
func (o *DeleteaspecificSubscriberRegistrationParams) WithID(id string) *DeleteaspecificSubscriberRegistrationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the deleteaspecific subscriber registration params
func (o *DeleteaspecificSubscriberRegistrationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteaspecificSubscriberRegistrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
