// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api1/models"
)

// GetaspecificSoundSetReader is a Reader for the GetaspecificSoundSet structure.
type GetaspecificSoundSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetaspecificSoundSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetaspecificSoundSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetaspecificSoundSetOK creates a GetaspecificSoundSetOK with default headers values
func NewGetaspecificSoundSetOK() *GetaspecificSoundSetOK {
	return &GetaspecificSoundSetOK{}
}

/*GetaspecificSoundSetOK handles this case with default header values.

GetaspecificSoundSetOK getaspecific sound set o k
*/
type GetaspecificSoundSetOK struct {
	Payload *models.SoundSets
}

func (o *GetaspecificSoundSetOK) Error() string {
	return fmt.Sprintf("[GET /soundsets/{id}][%d] getaspecificSoundSetOK  %+v", 200, o.Payload)
}

func (o *GetaspecificSoundSetOK) GetPayload() *models.SoundSets {
	return o.Payload
}

func (o *GetaspecificSoundSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SoundSets)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
