// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api1/models"
)

// GetaspecificBillingNetworkReader is a Reader for the GetaspecificBillingNetwork structure.
type GetaspecificBillingNetworkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetaspecificBillingNetworkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetaspecificBillingNetworkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetaspecificBillingNetworkOK creates a GetaspecificBillingNetworkOK with default headers values
func NewGetaspecificBillingNetworkOK() *GetaspecificBillingNetworkOK {
	return &GetaspecificBillingNetworkOK{}
}

/*GetaspecificBillingNetworkOK handles this case with default header values.

GetaspecificBillingNetworkOK getaspecific billing network o k
*/
type GetaspecificBillingNetworkOK struct {
	Payload *models.BillingNetworks
}

func (o *GetaspecificBillingNetworkOK) Error() string {
	return fmt.Sprintf("[GET /billingnetworks/{id}][%d] getaspecificBillingNetworkOK  %+v", 200, o.Payload)
}

func (o *GetaspecificBillingNetworkOK) GetPayload() *models.BillingNetworks {
	return o.Payload
}

func (o *GetaspecificBillingNetworkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BillingNetworks)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
