// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api1/models"
)

// ReplaceChangeaspecificSoundSetReader is a Reader for the ReplaceChangeaspecificSoundSet structure.
type ReplaceChangeaspecificSoundSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceChangeaspecificSoundSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReplaceChangeaspecificSoundSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReplaceChangeaspecificSoundSetOK creates a ReplaceChangeaspecificSoundSetOK with default headers values
func NewReplaceChangeaspecificSoundSetOK() *ReplaceChangeaspecificSoundSetOK {
	return &ReplaceChangeaspecificSoundSetOK{}
}

/*ReplaceChangeaspecificSoundSetOK handles this case with default header values.

ReplaceChangeaspecificSoundSetOK replace changeaspecific sound set o k
*/
type ReplaceChangeaspecificSoundSetOK struct {
	Payload *models.SoundSets
}

func (o *ReplaceChangeaspecificSoundSetOK) Error() string {
	return fmt.Sprintf("[PUT /soundsets/{id}][%d] replaceChangeaspecificSoundSetOK  %+v", 200, o.Payload)
}

func (o *ReplaceChangeaspecificSoundSetOK) GetPayload() *models.SoundSets {
	return o.Payload
}

func (o *ReplaceChangeaspecificSoundSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SoundSets)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
