// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReplaceChangeaspecificRtcNetworkParams creates a new ReplaceChangeaspecificRtcNetworkParams object
// with the default values initialized.
func NewReplaceChangeaspecificRtcNetworkParams() *ReplaceChangeaspecificRtcNetworkParams {
	var ()
	return &ReplaceChangeaspecificRtcNetworkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceChangeaspecificRtcNetworkParamsWithTimeout creates a new ReplaceChangeaspecificRtcNetworkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReplaceChangeaspecificRtcNetworkParamsWithTimeout(timeout time.Duration) *ReplaceChangeaspecificRtcNetworkParams {
	var ()
	return &ReplaceChangeaspecificRtcNetworkParams{

		timeout: timeout,
	}
}

// NewReplaceChangeaspecificRtcNetworkParamsWithContext creates a new ReplaceChangeaspecificRtcNetworkParams object
// with the default values initialized, and the ability to set a context for a request
func NewReplaceChangeaspecificRtcNetworkParamsWithContext(ctx context.Context) *ReplaceChangeaspecificRtcNetworkParams {
	var ()
	return &ReplaceChangeaspecificRtcNetworkParams{

		Context: ctx,
	}
}

// NewReplaceChangeaspecificRtcNetworkParamsWithHTTPClient creates a new ReplaceChangeaspecificRtcNetworkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReplaceChangeaspecificRtcNetworkParamsWithHTTPClient(client *http.Client) *ReplaceChangeaspecificRtcNetworkParams {
	var ()
	return &ReplaceChangeaspecificRtcNetworkParams{
		HTTPClient: client,
	}
}

/*ReplaceChangeaspecificRtcNetworkParams contains all the parameters to send to the API endpoint
for the replace changeaspecific rtc network operation typically these are written to a http.Request
*/
type ReplaceChangeaspecificRtcNetworkParams struct {

	/*Body*/
	Body *Replace1changeaspecificRtcNetworkRequest
	/*ContentType*/
	ContentType string
	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) WithTimeout(timeout time.Duration) *ReplaceChangeaspecificRtcNetworkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) WithContext(ctx context.Context) *ReplaceChangeaspecificRtcNetworkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) WithHTTPClient(client *http.Client) *ReplaceChangeaspecificRtcNetworkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) WithBody(body *Replace1changeaspecificRtcNetworkRequest) *ReplaceChangeaspecificRtcNetworkParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) SetBody(body *Replace1changeaspecificRtcNetworkRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) WithContentType(contentType string) *ReplaceChangeaspecificRtcNetworkParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithID adds the id to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) WithID(id string) *ReplaceChangeaspecificRtcNetworkParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the replace changeaspecific rtc network params
func (o *ReplaceChangeaspecificRtcNetworkParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceChangeaspecificRtcNetworkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
