// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api1/models"
)

// ReplaceChangeaspecificMailToFaxSettingReader is a Reader for the ReplaceChangeaspecificMailToFaxSetting structure.
type ReplaceChangeaspecificMailToFaxSettingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceChangeaspecificMailToFaxSettingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReplaceChangeaspecificMailToFaxSettingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReplaceChangeaspecificMailToFaxSettingOK creates a ReplaceChangeaspecificMailToFaxSettingOK with default headers values
func NewReplaceChangeaspecificMailToFaxSettingOK() *ReplaceChangeaspecificMailToFaxSettingOK {
	return &ReplaceChangeaspecificMailToFaxSettingOK{}
}

/*ReplaceChangeaspecificMailToFaxSettingOK handles this case with default header values.

ReplaceChangeaspecificMailToFaxSettingOK replace changeaspecific mail to fax setting o k
*/
type ReplaceChangeaspecificMailToFaxSettingOK struct {
	Payload *models.MailToFaxSettings2
}

func (o *ReplaceChangeaspecificMailToFaxSettingOK) Error() string {
	return fmt.Sprintf("[PUT /mailtofaxsettings/{id}][%d] replaceChangeaspecificMailToFaxSettingOK  %+v", 200, o.Payload)
}

func (o *ReplaceChangeaspecificMailToFaxSettingOK) GetPayload() *models.MailToFaxSettings2 {
	return o.Payload
}

func (o *ReplaceChangeaspecificMailToFaxSettingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MailToFaxSettings2)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
