// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ReplaceChangeaspecificCFMappingReader is a Reader for the ReplaceChangeaspecificCFMapping structure.
type ReplaceChangeaspecificCFMappingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceChangeaspecificCFMappingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewReplaceChangeaspecificCFMappingNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReplaceChangeaspecificCFMappingNoContent creates a ReplaceChangeaspecificCFMappingNoContent with default headers values
func NewReplaceChangeaspecificCFMappingNoContent() *ReplaceChangeaspecificCFMappingNoContent {
	return &ReplaceChangeaspecificCFMappingNoContent{}
}

/*ReplaceChangeaspecificCFMappingNoContent handles this case with default header values.

ReplaceChangeaspecificCFMappingNoContent replace changeaspecific c f mapping no content
*/
type ReplaceChangeaspecificCFMappingNoContent struct {
	Payload interface{}
}

func (o *ReplaceChangeaspecificCFMappingNoContent) Error() string {
	return fmt.Sprintf("[PUT /cfmappings/{id}][%d] replaceChangeaspecificCFMappingNoContent  %+v", 204, o.Payload)
}

func (o *ReplaceChangeaspecificCFMappingNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *ReplaceChangeaspecificCFMappingNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
