// Code generated by go-swagger; DO NOT EDIT.

package sms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api/models"
)

// NewCreateanewSMSParams creates a new CreateanewSMSParams object
// with the default values initialized.
func NewCreateanewSMSParams() *CreateanewSMSParams {
	var ()
	return &CreateanewSMSParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateanewSMSParamsWithTimeout creates a new CreateanewSMSParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateanewSMSParamsWithTimeout(timeout time.Duration) *CreateanewSMSParams {
	var ()
	return &CreateanewSMSParams{

		timeout: timeout,
	}
}

// NewCreateanewSMSParamsWithContext creates a new CreateanewSMSParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateanewSMSParamsWithContext(ctx context.Context) *CreateanewSMSParams {
	var ()
	return &CreateanewSMSParams{

		Context: ctx,
	}
}

// NewCreateanewSMSParamsWithHTTPClient creates a new CreateanewSMSParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateanewSMSParamsWithHTTPClient(client *http.Client) *CreateanewSMSParams {
	var ()
	return &CreateanewSMSParams{
		HTTPClient: client,
	}
}

/*CreateanewSMSParams contains all the parameters to send to the API endpoint
for the createanew s m s operation typically these are written to a http.Request
*/
type CreateanewSMSParams struct {

	/*Body*/
	Body *models.CreateanewSMSRequest
	/*ContentType*/
	ContentType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the createanew s m s params
func (o *CreateanewSMSParams) WithTimeout(timeout time.Duration) *CreateanewSMSParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the createanew s m s params
func (o *CreateanewSMSParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the createanew s m s params
func (o *CreateanewSMSParams) WithContext(ctx context.Context) *CreateanewSMSParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the createanew s m s params
func (o *CreateanewSMSParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the createanew s m s params
func (o *CreateanewSMSParams) WithHTTPClient(client *http.Client) *CreateanewSMSParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the createanew s m s params
func (o *CreateanewSMSParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the createanew s m s params
func (o *CreateanewSMSParams) WithBody(body *models.CreateanewSMSRequest) *CreateanewSMSParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the createanew s m s params
func (o *CreateanewSMSParams) SetBody(body *models.CreateanewSMSRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the createanew s m s params
func (o *CreateanewSMSParams) WithContentType(contentType string) *CreateanewSMSParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the createanew s m s params
func (o *CreateanewSMSParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WriteToRequest writes these params to a swagger request
func (o *CreateanewSMSParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
