// Code generated by go-swagger; DO NOT EDIT.

package callrecordingstreams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new callrecordingstreams API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for callrecordingstreams API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetCallRecordingStreamitems(params *GetCallRecordingStreamitemsParams) (*GetCallRecordingStreamitemsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetCallRecordingStreamitems gets call recording stream items
*/
func (a *Client) GetCallRecordingStreamitems(params *GetCallRecordingStreamitemsParams) (*GetCallRecordingStreamitemsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCallRecordingStreamitemsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetCallRecordingStreamitems",
		Method:             "GET",
		PathPattern:        "/callrecordingstreams",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCallRecordingStreamitemsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCallRecordingStreamitemsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCallRecordingStreamitems: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
