// Code generated by go-swagger; DO NOT EDIT.

package billingfees

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new billingfees API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for billingfees API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	CreateanewBillingFee(params *CreateanewBillingFeeParams) (*CreateanewBillingFeeCreated, error)

	GetBillingFeeitems(params *GetBillingFeeitemsParams) (*GetBillingFeeitemsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CreateanewBillingFee creates a new billing fee
*/
func (a *Client) CreateanewBillingFee(params *CreateanewBillingFeeParams) (*CreateanewBillingFeeCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateanewBillingFeeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "CreateanewBillingFee",
		Method:             "POST",
		PathPattern:        "/billingfees",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateanewBillingFeeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateanewBillingFeeCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateanewBillingFee: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetBillingFeeitems gets billing fee items
*/
func (a *Client) GetBillingFeeitems(params *GetBillingFeeitemsParams) (*GetBillingFeeitemsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBillingFeeitemsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetBillingFeeitems",
		Method:             "GET",
		PathPattern:        "/billingfees",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetBillingFeeitemsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetBillingFeeitemsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetBillingFeeitems: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
