// Code generated by go-swagger; DO NOT EDIT.

package billingfees

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/negbie/ngcp-api/models"
)

// GetBillingFeeitemsReader is a Reader for the GetBillingFeeitems structure.
type GetBillingFeeitemsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBillingFeeitemsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBillingFeeitemsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetBillingFeeitemsOK creates a GetBillingFeeitemsOK with default headers values
func NewGetBillingFeeitemsOK() *GetBillingFeeitemsOK {
	return &GetBillingFeeitemsOK{}
}

/*GetBillingFeeitemsOK handles this case with default header values.

GetBillingFeeitemsOK get billing feeitems o k
*/
type GetBillingFeeitemsOK struct {
	Payload []*models.BillingFees
}

func (o *GetBillingFeeitemsOK) Error() string {
	return fmt.Sprintf("[GET /billingfees][%d] getBillingFeeitemsOK  %+v", 200, o.Payload)
}

func (o *GetBillingFeeitemsOK) GetPayload() []*models.BillingFees {
	return o.Payload
}

func (o *GetBillingFeeitemsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
