// Code generated by go-swagger; DO NOT EDIT.

package balanceintervals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new balanceintervals API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for balanceintervals API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
BalanceintervalsByIDGet gets a specific balance interval

TODO: Add Description
*/
func (a *Client) BalanceintervalsByIDGet(params *BalanceintervalsByIDGetParams) (*BalanceintervalsByIDGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewBalanceintervalsByIDGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "BalanceintervalsByIdGet",
		Method:             "GET",
		PathPattern:        "/balanceintervals/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &BalanceintervalsByIDGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*BalanceintervalsByIDGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for BalanceintervalsByIdGet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
BalanceintervalsGet gets balance interval items

TODO: Add Description
*/
func (a *Client) BalanceintervalsGet(params *BalanceintervalsGetParams) (*BalanceintervalsGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewBalanceintervalsGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "BalanceintervalsGet",
		Method:             "GET",
		PathPattern:        "/balanceintervals",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &BalanceintervalsGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*BalanceintervalsGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for BalanceintervalsGet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
