// Code generated by go-swagger; DO NOT EDIT.

package pbxdeviceprofilepreferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPbxdeviceprofilepreferencesGetParams creates a new PbxdeviceprofilepreferencesGetParams object
// with the default values initialized.
func NewPbxdeviceprofilepreferencesGetParams() *PbxdeviceprofilepreferencesGetParams {
	var ()
	return &PbxdeviceprofilepreferencesGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPbxdeviceprofilepreferencesGetParamsWithTimeout creates a new PbxdeviceprofilepreferencesGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPbxdeviceprofilepreferencesGetParamsWithTimeout(timeout time.Duration) *PbxdeviceprofilepreferencesGetParams {
	var ()
	return &PbxdeviceprofilepreferencesGetParams{

		timeout: timeout,
	}
}

// NewPbxdeviceprofilepreferencesGetParamsWithContext creates a new PbxdeviceprofilepreferencesGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewPbxdeviceprofilepreferencesGetParamsWithContext(ctx context.Context) *PbxdeviceprofilepreferencesGetParams {
	var ()
	return &PbxdeviceprofilepreferencesGetParams{

		Context: ctx,
	}
}

// NewPbxdeviceprofilepreferencesGetParamsWithHTTPClient creates a new PbxdeviceprofilepreferencesGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPbxdeviceprofilepreferencesGetParamsWithHTTPClient(client *http.Client) *PbxdeviceprofilepreferencesGetParams {
	var ()
	return &PbxdeviceprofilepreferencesGetParams{
		HTTPClient: client,
	}
}

/*PbxdeviceprofilepreferencesGetParams contains all the parameters to send to the API endpoint
for the pbxdeviceprofilepreferences get operation typically these are written to a http.Request
*/
type PbxdeviceprofilepreferencesGetParams struct {

	/*OrderBy
	  Order collection by a specific attribute.

	*/
	OrderBy string
	/*OrderByDirection
	  Direction which the collection should be ordered by. Possible values are: asc (default), desc.

	*/
	OrderByDirection string
	/*Page
	  Pagination page which should be displayed (default: 1)

	*/
	Page string
	/*Rows
	  Number of rows in one pagination page (default: 10)

	*/
	Rows string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) WithTimeout(timeout time.Duration) *PbxdeviceprofilepreferencesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) WithContext(ctx context.Context) *PbxdeviceprofilepreferencesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) WithHTTPClient(client *http.Client) *PbxdeviceprofilepreferencesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderBy adds the orderBy to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) WithOrderBy(orderBy string) *PbxdeviceprofilepreferencesGetParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) SetOrderBy(orderBy string) {
	o.OrderBy = orderBy
}

// WithOrderByDirection adds the orderByDirection to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) WithOrderByDirection(orderByDirection string) *PbxdeviceprofilepreferencesGetParams {
	o.SetOrderByDirection(orderByDirection)
	return o
}

// SetOrderByDirection adds the orderByDirection to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) SetOrderByDirection(orderByDirection string) {
	o.OrderByDirection = orderByDirection
}

// WithPage adds the page to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) WithPage(page string) *PbxdeviceprofilepreferencesGetParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) SetPage(page string) {
	o.Page = page
}

// WithRows adds the rows to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) WithRows(rows string) *PbxdeviceprofilepreferencesGetParams {
	o.SetRows(rows)
	return o
}

// SetRows adds the rows to the pbxdeviceprofilepreferences get params
func (o *PbxdeviceprofilepreferencesGetParams) SetRows(rows string) {
	o.Rows = rows
}

// WriteToRequest writes these params to a swagger request
func (o *PbxdeviceprofilepreferencesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param order_by
	qrOrderBy := o.OrderBy
	qOrderBy := qrOrderBy
	if qOrderBy != "" {
		if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
			return err
		}
	}

	// query param order_by_direction
	qrOrderByDirection := o.OrderByDirection
	qOrderByDirection := qrOrderByDirection
	if qOrderByDirection != "" {
		if err := r.SetQueryParam("order_by_direction", qOrderByDirection); err != nil {
			return err
		}
	}

	// query param page
	qrPage := o.Page
	qPage := qrPage
	if qPage != "" {
		if err := r.SetQueryParam("page", qPage); err != nil {
			return err
		}
	}

	// query param rows
	qrRows := o.Rows
	qRows := qrRows
	if qRows != "" {
		if err := r.SetQueryParam("rows", qRows); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
