// Code generated by go-swagger; DO NOT EDIT.

package pbxfielddevicepreferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PbxfielddevicepreferencesGetReader is a Reader for the PbxfielddevicepreferencesGet structure.
type PbxfielddevicepreferencesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PbxfielddevicepreferencesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPbxfielddevicepreferencesGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPbxfielddevicepreferencesGetOK creates a PbxfielddevicepreferencesGetOK with default headers values
func NewPbxfielddevicepreferencesGetOK() *PbxfielddevicepreferencesGetOK {
	return &PbxfielddevicepreferencesGetOK{}
}

/*PbxfielddevicepreferencesGetOK handles this case with default header values.

PbxfielddevicepreferencesGetOK pbxfielddevicepreferences get o k
*/
type PbxfielddevicepreferencesGetOK struct {
	Payload []string
}

func (o *PbxfielddevicepreferencesGetOK) Error() string {
	return fmt.Sprintf("[GET /pbxfielddevicepreferences][%d] pbxfielddevicepreferencesGetOK  %+v", 200, o.Payload)
}

func (o *PbxfielddevicepreferencesGetOK) GetPayload() []string {
	return o.Payload
}

func (o *PbxfielddevicepreferencesGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
