// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/negbie/ngcp-api/models"
)

// BillingprofilesGetReader is a Reader for the BillingprofilesGet structure.
type BillingprofilesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BillingprofilesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBillingprofilesGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBillingprofilesGetOK creates a BillingprofilesGetOK with default headers values
func NewBillingprofilesGetOK() *BillingprofilesGetOK {
	return &BillingprofilesGetOK{}
}

/*BillingprofilesGetOK handles this case with default header values.

BillingprofilesGetOK billingprofiles get o k
*/
type BillingprofilesGetOK struct {
	Payload []*models.BillingProfile7
}

func (o *BillingprofilesGetOK) Error() string {
	return fmt.Sprintf("[GET /billingprofiles][%d] billingprofilesGetOK  %+v", 200, o.Payload)
}

func (o *BillingprofilesGetOK) GetPayload() []*models.BillingProfile7 {
	return o.Payload
}

func (o *BillingprofilesGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
