// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/negbie/ngcp-api/models"
)

// BillingfeesGetReader is a Reader for the BillingfeesGet structure.
type BillingfeesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BillingfeesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBillingfeesGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBillingfeesGetOK creates a BillingfeesGetOK with default headers values
func NewBillingfeesGetOK() *BillingfeesGetOK {
	return &BillingfeesGetOK{}
}

/*BillingfeesGetOK handles this case with default header values.

BillingfeesGetOK billingfees get o k
*/
type BillingfeesGetOK struct {
	Payload []*models.BillingFee
}

func (o *BillingfeesGetOK) Error() string {
	return fmt.Sprintf("[GET /billingfees][%d] billingfeesGetOK  %+v", 200, o.Payload)
}

func (o *BillingfeesGetOK) GetPayload() []*models.BillingFee {
	return o.Payload
}

func (o *BillingfeesGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
