// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmergencymappingsGetParams creates a new EmergencymappingsGetParams object
// with the default values initialized.
func NewEmergencymappingsGetParams() *EmergencymappingsGetParams {
	var ()
	return &EmergencymappingsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmergencymappingsGetParamsWithTimeout creates a new EmergencymappingsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmergencymappingsGetParamsWithTimeout(timeout time.Duration) *EmergencymappingsGetParams {
	var ()
	return &EmergencymappingsGetParams{

		timeout: timeout,
	}
}

// NewEmergencymappingsGetParamsWithContext creates a new EmergencymappingsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmergencymappingsGetParamsWithContext(ctx context.Context) *EmergencymappingsGetParams {
	var ()
	return &EmergencymappingsGetParams{

		Context: ctx,
	}
}

// NewEmergencymappingsGetParamsWithHTTPClient creates a new EmergencymappingsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmergencymappingsGetParamsWithHTTPClient(client *http.Client) *EmergencymappingsGetParams {
	var ()
	return &EmergencymappingsGetParams{
		HTTPClient: client,
	}
}

/*EmergencymappingsGetParams contains all the parameters to send to the API endpoint
for the emergencymappings get operation typically these are written to a http.Request
*/
type EmergencymappingsGetParams struct {

	/*Code
	  Filter for mappings with a specific code (wildcards possible)

	*/
	Code string
	/*EmergencyContainerID
	  Filter for emergency mappings belonging to a specific emergency mapping container

	*/
	EmergencyContainerID string
	/*OrderBy
	  Order collection by a specific attribute.

	*/
	OrderBy string
	/*OrderByDirection
	  Direction which the collection should be ordered by. Possible values are: asc (default), desc.

	*/
	OrderByDirection string
	/*Page
	  Pagination page which should be displayed (default: 1)

	*/
	Page string
	/*ResellerID
	  Filter for emergency mappings belonging to a specific reseller

	*/
	ResellerID string
	/*Rows
	  Number of rows in one pagination page (default: 10)

	*/
	Rows string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the emergencymappings get params
func (o *EmergencymappingsGetParams) WithTimeout(timeout time.Duration) *EmergencymappingsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the emergencymappings get params
func (o *EmergencymappingsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the emergencymappings get params
func (o *EmergencymappingsGetParams) WithContext(ctx context.Context) *EmergencymappingsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the emergencymappings get params
func (o *EmergencymappingsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the emergencymappings get params
func (o *EmergencymappingsGetParams) WithHTTPClient(client *http.Client) *EmergencymappingsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the emergencymappings get params
func (o *EmergencymappingsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCode adds the code to the emergencymappings get params
func (o *EmergencymappingsGetParams) WithCode(code string) *EmergencymappingsGetParams {
	o.SetCode(code)
	return o
}

// SetCode adds the code to the emergencymappings get params
func (o *EmergencymappingsGetParams) SetCode(code string) {
	o.Code = code
}

// WithEmergencyContainerID adds the emergencyContainerID to the emergencymappings get params
func (o *EmergencymappingsGetParams) WithEmergencyContainerID(emergencyContainerID string) *EmergencymappingsGetParams {
	o.SetEmergencyContainerID(emergencyContainerID)
	return o
}

// SetEmergencyContainerID adds the emergencyContainerId to the emergencymappings get params
func (o *EmergencymappingsGetParams) SetEmergencyContainerID(emergencyContainerID string) {
	o.EmergencyContainerID = emergencyContainerID
}

// WithOrderBy adds the orderBy to the emergencymappings get params
func (o *EmergencymappingsGetParams) WithOrderBy(orderBy string) *EmergencymappingsGetParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the emergencymappings get params
func (o *EmergencymappingsGetParams) SetOrderBy(orderBy string) {
	o.OrderBy = orderBy
}

// WithOrderByDirection adds the orderByDirection to the emergencymappings get params
func (o *EmergencymappingsGetParams) WithOrderByDirection(orderByDirection string) *EmergencymappingsGetParams {
	o.SetOrderByDirection(orderByDirection)
	return o
}

// SetOrderByDirection adds the orderByDirection to the emergencymappings get params
func (o *EmergencymappingsGetParams) SetOrderByDirection(orderByDirection string) {
	o.OrderByDirection = orderByDirection
}

// WithPage adds the page to the emergencymappings get params
func (o *EmergencymappingsGetParams) WithPage(page string) *EmergencymappingsGetParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the emergencymappings get params
func (o *EmergencymappingsGetParams) SetPage(page string) {
	o.Page = page
}

// WithResellerID adds the resellerID to the emergencymappings get params
func (o *EmergencymappingsGetParams) WithResellerID(resellerID string) *EmergencymappingsGetParams {
	o.SetResellerID(resellerID)
	return o
}

// SetResellerID adds the resellerId to the emergencymappings get params
func (o *EmergencymappingsGetParams) SetResellerID(resellerID string) {
	o.ResellerID = resellerID
}

// WithRows adds the rows to the emergencymappings get params
func (o *EmergencymappingsGetParams) WithRows(rows string) *EmergencymappingsGetParams {
	o.SetRows(rows)
	return o
}

// SetRows adds the rows to the emergencymappings get params
func (o *EmergencymappingsGetParams) SetRows(rows string) {
	o.Rows = rows
}

// WriteToRequest writes these params to a swagger request
func (o *EmergencymappingsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param code
	qrCode := o.Code
	qCode := qrCode
	if qCode != "" {
		if err := r.SetQueryParam("code", qCode); err != nil {
			return err
		}
	}

	// query param emergency_container_id
	qrEmergencyContainerID := o.EmergencyContainerID
	qEmergencyContainerID := qrEmergencyContainerID
	if qEmergencyContainerID != "" {
		if err := r.SetQueryParam("emergency_container_id", qEmergencyContainerID); err != nil {
			return err
		}
	}

	// query param order_by
	qrOrderBy := o.OrderBy
	qOrderBy := qrOrderBy
	if qOrderBy != "" {
		if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
			return err
		}
	}

	// query param order_by_direction
	qrOrderByDirection := o.OrderByDirection
	qOrderByDirection := qrOrderByDirection
	if qOrderByDirection != "" {
		if err := r.SetQueryParam("order_by_direction", qOrderByDirection); err != nil {
			return err
		}
	}

	// query param page
	qrPage := o.Page
	qPage := qrPage
	if qPage != "" {
		if err := r.SetQueryParam("page", qPage); err != nil {
			return err
		}
	}

	// query param reseller_id
	qrResellerID := o.ResellerID
	qResellerID := qrResellerID
	if qResellerID != "" {
		if err := r.SetQueryParam("reseller_id", qResellerID); err != nil {
			return err
		}
	}

	// query param rows
	qrRows := o.Rows
	qRows := qrRows
	if qRows != "" {
		if err := r.SetQueryParam("rows", qRows); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
