// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewResellersGetParams creates a new ResellersGetParams object
// with the default values initialized.
func NewResellersGetParams() *ResellersGetParams {
	var ()
	return &ResellersGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewResellersGetParamsWithTimeout creates a new ResellersGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewResellersGetParamsWithTimeout(timeout time.Duration) *ResellersGetParams {
	var ()
	return &ResellersGetParams{

		timeout: timeout,
	}
}

// NewResellersGetParamsWithContext creates a new ResellersGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewResellersGetParamsWithContext(ctx context.Context) *ResellersGetParams {
	var ()
	return &ResellersGetParams{

		Context: ctx,
	}
}

// NewResellersGetParamsWithHTTPClient creates a new ResellersGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewResellersGetParamsWithHTTPClient(client *http.Client) *ResellersGetParams {
	var ()
	return &ResellersGetParams{
		HTTPClient: client,
	}
}

/*ResellersGetParams contains all the parameters to send to the API endpoint
for the resellers get operation typically these are written to a http.Request
*/
type ResellersGetParams struct {

	/*Name
	  Filter for resellers matching the given name pattern

	*/
	Name string
	/*OrderBy
	  Order collection by a specific attribute.

	*/
	OrderBy string
	/*OrderByDirection
	  Direction which the collection should be ordered by. Possible values are: asc (default), desc.

	*/
	OrderByDirection string
	/*Page
	  Pagination page which should be displayed (default: 1)

	*/
	Page string
	/*Rows
	  Number of rows in one pagination page (default: 10)

	*/
	Rows string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the resellers get params
func (o *ResellersGetParams) WithTimeout(timeout time.Duration) *ResellersGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resellers get params
func (o *ResellersGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resellers get params
func (o *ResellersGetParams) WithContext(ctx context.Context) *ResellersGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resellers get params
func (o *ResellersGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resellers get params
func (o *ResellersGetParams) WithHTTPClient(client *http.Client) *ResellersGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resellers get params
func (o *ResellersGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the resellers get params
func (o *ResellersGetParams) WithName(name string) *ResellersGetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the resellers get params
func (o *ResellersGetParams) SetName(name string) {
	o.Name = name
}

// WithOrderBy adds the orderBy to the resellers get params
func (o *ResellersGetParams) WithOrderBy(orderBy string) *ResellersGetParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the resellers get params
func (o *ResellersGetParams) SetOrderBy(orderBy string) {
	o.OrderBy = orderBy
}

// WithOrderByDirection adds the orderByDirection to the resellers get params
func (o *ResellersGetParams) WithOrderByDirection(orderByDirection string) *ResellersGetParams {
	o.SetOrderByDirection(orderByDirection)
	return o
}

// SetOrderByDirection adds the orderByDirection to the resellers get params
func (o *ResellersGetParams) SetOrderByDirection(orderByDirection string) {
	o.OrderByDirection = orderByDirection
}

// WithPage adds the page to the resellers get params
func (o *ResellersGetParams) WithPage(page string) *ResellersGetParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the resellers get params
func (o *ResellersGetParams) SetPage(page string) {
	o.Page = page
}

// WithRows adds the rows to the resellers get params
func (o *ResellersGetParams) WithRows(rows string) *ResellersGetParams {
	o.SetRows(rows)
	return o
}

// SetRows adds the rows to the resellers get params
func (o *ResellersGetParams) SetRows(rows string) {
	o.Rows = rows
}

// WriteToRequest writes these params to a swagger request
func (o *ResellersGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {
		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	// query param order_by
	qrOrderBy := o.OrderBy
	qOrderBy := qrOrderBy
	if qOrderBy != "" {
		if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
			return err
		}
	}

	// query param order_by_direction
	qrOrderByDirection := o.OrderByDirection
	qOrderByDirection := qrOrderByDirection
	if qOrderByDirection != "" {
		if err := r.SetQueryParam("order_by_direction", qOrderByDirection); err != nil {
			return err
		}
	}

	// query param page
	qrPage := o.Page
	qPage := qrPage
	if qPage != "" {
		if err := r.SetQueryParam("page", qPage); err != nil {
			return err
		}
	}

	// query param rows
	qrRows := o.Rows
	qRows := qrRows
	if qRows != "" {
		if err := r.SetQueryParam("rows", qRows); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
