// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/negbie/ngcp-api/models"
)

// NewRewriterulesPostParams creates a new RewriterulesPostParams object
// with the default values initialized.
func NewRewriterulesPostParams() *RewriterulesPostParams {
	var ()
	return &RewriterulesPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRewriterulesPostParamsWithTimeout creates a new RewriterulesPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRewriterulesPostParamsWithTimeout(timeout time.Duration) *RewriterulesPostParams {
	var ()
	return &RewriterulesPostParams{

		timeout: timeout,
	}
}

// NewRewriterulesPostParamsWithContext creates a new RewriterulesPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewRewriterulesPostParamsWithContext(ctx context.Context) *RewriterulesPostParams {
	var ()
	return &RewriterulesPostParams{

		Context: ctx,
	}
}

// NewRewriterulesPostParamsWithHTTPClient creates a new RewriterulesPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRewriterulesPostParamsWithHTTPClient(client *http.Client) *RewriterulesPostParams {
	var ()
	return &RewriterulesPostParams{
		HTTPClient: client,
	}
}

/*RewriterulesPostParams contains all the parameters to send to the API endpoint
for the rewriterules post operation typically these are written to a http.Request
*/
type RewriterulesPostParams struct {

	/*Body*/
	Body *models.CreateanewRewriteRuleRequest
	/*ContentType*/
	ContentType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the rewriterules post params
func (o *RewriterulesPostParams) WithTimeout(timeout time.Duration) *RewriterulesPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rewriterules post params
func (o *RewriterulesPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rewriterules post params
func (o *RewriterulesPostParams) WithContext(ctx context.Context) *RewriterulesPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rewriterules post params
func (o *RewriterulesPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rewriterules post params
func (o *RewriterulesPostParams) WithHTTPClient(client *http.Client) *RewriterulesPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rewriterules post params
func (o *RewriterulesPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the rewriterules post params
func (o *RewriterulesPostParams) WithBody(body *models.CreateanewRewriteRuleRequest) *RewriterulesPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the rewriterules post params
func (o *RewriterulesPostParams) SetBody(body *models.CreateanewRewriteRuleRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the rewriterules post params
func (o *RewriterulesPostParams) WithContentType(contentType string) *RewriterulesPostParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the rewriterules post params
func (o *RewriterulesPostParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WriteToRequest writes these params to a swagger request
func (o *RewriterulesPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
