// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSystemcontactsGetParams creates a new SystemcontactsGetParams object
// with the default values initialized.
func NewSystemcontactsGetParams() *SystemcontactsGetParams {
	var ()
	return &SystemcontactsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSystemcontactsGetParamsWithTimeout creates a new SystemcontactsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSystemcontactsGetParamsWithTimeout(timeout time.Duration) *SystemcontactsGetParams {
	var ()
	return &SystemcontactsGetParams{

		timeout: timeout,
	}
}

// NewSystemcontactsGetParamsWithContext creates a new SystemcontactsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewSystemcontactsGetParamsWithContext(ctx context.Context) *SystemcontactsGetParams {
	var ()
	return &SystemcontactsGetParams{

		Context: ctx,
	}
}

// NewSystemcontactsGetParamsWithHTTPClient creates a new SystemcontactsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSystemcontactsGetParamsWithHTTPClient(client *http.Client) *SystemcontactsGetParams {
	var ()
	return &SystemcontactsGetParams{
		HTTPClient: client,
	}
}

/*SystemcontactsGetParams contains all the parameters to send to the API endpoint
for the systemcontacts get operation typically these are written to a http.Request
*/
type SystemcontactsGetParams struct {

	/*Email
	  Filter for contacts matching an email pattern

	*/
	Email string
	/*OrderBy
	  Order collection by a specific attribute.

	*/
	OrderBy string
	/*OrderByDirection
	  Direction which the collection should be ordered by. Possible values are: asc (default), desc.

	*/
	OrderByDirection string
	/*Page
	  Pagination page which should be displayed (default: 1)

	*/
	Page string
	/*Rows
	  Number of rows in one pagination page (default: 10)

	*/
	Rows string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the systemcontacts get params
func (o *SystemcontactsGetParams) WithTimeout(timeout time.Duration) *SystemcontactsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the systemcontacts get params
func (o *SystemcontactsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the systemcontacts get params
func (o *SystemcontactsGetParams) WithContext(ctx context.Context) *SystemcontactsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the systemcontacts get params
func (o *SystemcontactsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the systemcontacts get params
func (o *SystemcontactsGetParams) WithHTTPClient(client *http.Client) *SystemcontactsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the systemcontacts get params
func (o *SystemcontactsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the systemcontacts get params
func (o *SystemcontactsGetParams) WithEmail(email string) *SystemcontactsGetParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the systemcontacts get params
func (o *SystemcontactsGetParams) SetEmail(email string) {
	o.Email = email
}

// WithOrderBy adds the orderBy to the systemcontacts get params
func (o *SystemcontactsGetParams) WithOrderBy(orderBy string) *SystemcontactsGetParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the systemcontacts get params
func (o *SystemcontactsGetParams) SetOrderBy(orderBy string) {
	o.OrderBy = orderBy
}

// WithOrderByDirection adds the orderByDirection to the systemcontacts get params
func (o *SystemcontactsGetParams) WithOrderByDirection(orderByDirection string) *SystemcontactsGetParams {
	o.SetOrderByDirection(orderByDirection)
	return o
}

// SetOrderByDirection adds the orderByDirection to the systemcontacts get params
func (o *SystemcontactsGetParams) SetOrderByDirection(orderByDirection string) {
	o.OrderByDirection = orderByDirection
}

// WithPage adds the page to the systemcontacts get params
func (o *SystemcontactsGetParams) WithPage(page string) *SystemcontactsGetParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the systemcontacts get params
func (o *SystemcontactsGetParams) SetPage(page string) {
	o.Page = page
}

// WithRows adds the rows to the systemcontacts get params
func (o *SystemcontactsGetParams) WithRows(rows string) *SystemcontactsGetParams {
	o.SetRows(rows)
	return o
}

// SetRows adds the rows to the systemcontacts get params
func (o *SystemcontactsGetParams) SetRows(rows string) {
	o.Rows = rows
}

// WriteToRequest writes these params to a swagger request
func (o *SystemcontactsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param email
	qrEmail := o.Email
	qEmail := qrEmail
	if qEmail != "" {
		if err := r.SetQueryParam("email", qEmail); err != nil {
			return err
		}
	}

	// query param order_by
	qrOrderBy := o.OrderBy
	qOrderBy := qrOrderBy
	if qOrderBy != "" {
		if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
			return err
		}
	}

	// query param order_by_direction
	qrOrderByDirection := o.OrderByDirection
	qOrderByDirection := qrOrderByDirection
	if qOrderByDirection != "" {
		if err := r.SetQueryParam("order_by_direction", qOrderByDirection); err != nil {
			return err
		}
	}

	// query param page
	qrPage := o.Page
	qPage := qrPage
	if qPage != "" {
		if err := r.SetQueryParam("page", qPage); err != nil {
			return err
		}
	}

	// query param rows
	qrRows := o.Rows
	qRows := qrRows
	if qRows != "" {
		if err := r.SetQueryParam("rows", qRows); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
