// Code generated by go-swagger; DO NOT EDIT.

package voicemailgreetings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetVoicemailGreetingitemsParams creates a new GetVoicemailGreetingitemsParams object
// with the default values initialized.
func NewGetVoicemailGreetingitemsParams() *GetVoicemailGreetingitemsParams {
	var ()
	return &GetVoicemailGreetingitemsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVoicemailGreetingitemsParamsWithTimeout creates a new GetVoicemailGreetingitemsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVoicemailGreetingitemsParamsWithTimeout(timeout time.Duration) *GetVoicemailGreetingitemsParams {
	var ()
	return &GetVoicemailGreetingitemsParams{

		timeout: timeout,
	}
}

// NewGetVoicemailGreetingitemsParamsWithContext creates a new GetVoicemailGreetingitemsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVoicemailGreetingitemsParamsWithContext(ctx context.Context) *GetVoicemailGreetingitemsParams {
	var ()
	return &GetVoicemailGreetingitemsParams{

		Context: ctx,
	}
}

// NewGetVoicemailGreetingitemsParamsWithHTTPClient creates a new GetVoicemailGreetingitemsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetVoicemailGreetingitemsParamsWithHTTPClient(client *http.Client) *GetVoicemailGreetingitemsParams {
	var ()
	return &GetVoicemailGreetingitemsParams{
		HTTPClient: client,
	}
}

/*GetVoicemailGreetingitemsParams contains all the parameters to send to the API endpoint
for the get voicemail greetingitems operation typically these are written to a http.Request
*/
type GetVoicemailGreetingitemsParams struct {

	/*OrderBy
	  Order collection by a specific attribute.

	*/
	OrderBy string
	/*OrderByDirection
	  Direction which the collection should be ordered by. Possible values are: asc (default), desc.

	*/
	OrderByDirection string
	/*Page
	  Pagination page which should be displayed (default: 1)

	*/
	Page string
	/*Rows
	  Number of rows in one pagination page (default: 10)

	*/
	Rows string
	/*SubscriberID
	  Filter for registrations of a specific subscriber

	*/
	SubscriberID string
	/*Type
	  Filter for the greeting type

	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) WithTimeout(timeout time.Duration) *GetVoicemailGreetingitemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) WithContext(ctx context.Context) *GetVoicemailGreetingitemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) WithHTTPClient(client *http.Client) *GetVoicemailGreetingitemsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderBy adds the orderBy to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) WithOrderBy(orderBy string) *GetVoicemailGreetingitemsParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) SetOrderBy(orderBy string) {
	o.OrderBy = orderBy
}

// WithOrderByDirection adds the orderByDirection to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) WithOrderByDirection(orderByDirection string) *GetVoicemailGreetingitemsParams {
	o.SetOrderByDirection(orderByDirection)
	return o
}

// SetOrderByDirection adds the orderByDirection to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) SetOrderByDirection(orderByDirection string) {
	o.OrderByDirection = orderByDirection
}

// WithPage adds the page to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) WithPage(page string) *GetVoicemailGreetingitemsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) SetPage(page string) {
	o.Page = page
}

// WithRows adds the rows to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) WithRows(rows string) *GetVoicemailGreetingitemsParams {
	o.SetRows(rows)
	return o
}

// SetRows adds the rows to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) SetRows(rows string) {
	o.Rows = rows
}

// WithSubscriberID adds the subscriberID to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) WithSubscriberID(subscriberID string) *GetVoicemailGreetingitemsParams {
	o.SetSubscriberID(subscriberID)
	return o
}

// SetSubscriberID adds the subscriberId to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) SetSubscriberID(subscriberID string) {
	o.SubscriberID = subscriberID
}

// WithType adds the typeVar to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) WithType(typeVar string) *GetVoicemailGreetingitemsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get voicemail greetingitems params
func (o *GetVoicemailGreetingitemsParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetVoicemailGreetingitemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param order_by
	qrOrderBy := o.OrderBy
	qOrderBy := qrOrderBy
	if qOrderBy != "" {
		if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
			return err
		}
	}

	// query param order_by_direction
	qrOrderByDirection := o.OrderByDirection
	qOrderByDirection := qrOrderByDirection
	if qOrderByDirection != "" {
		if err := r.SetQueryParam("order_by_direction", qOrderByDirection); err != nil {
			return err
		}
	}

	// query param page
	qrPage := o.Page
	qPage := qrPage
	if qPage != "" {
		if err := r.SetQueryParam("page", qPage); err != nil {
			return err
		}
	}

	// query param rows
	qrRows := o.Rows
	qRows := qrRows
	if qRows != "" {
		if err := r.SetQueryParam("rows", qRows); err != nil {
			return err
		}
	}

	// query param subscriber_id
	qrSubscriberID := o.SubscriberID
	qSubscriberID := qrSubscriberID
	if qSubscriberID != "" {
		if err := r.SetQueryParam("subscriber_id", qSubscriberID); err != nil {
			return err
		}
	}

	// query param type
	qrType := o.Type
	qType := qrType
	if qType != "" {
		if err := r.SetQueryParam("type", qType); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
