// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEventsByIDGetParams creates a new EventsByIDGetParams object
// with the default values initialized.
func NewEventsByIDGetParams() *EventsByIDGetParams {
	var ()
	return &EventsByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEventsByIDGetParamsWithTimeout creates a new EventsByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEventsByIDGetParamsWithTimeout(timeout time.Duration) *EventsByIDGetParams {
	var ()
	return &EventsByIDGetParams{

		timeout: timeout,
	}
}

// NewEventsByIDGetParamsWithContext creates a new EventsByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewEventsByIDGetParamsWithContext(ctx context.Context) *EventsByIDGetParams {
	var ()
	return &EventsByIDGetParams{

		Context: ctx,
	}
}

// NewEventsByIDGetParamsWithHTTPClient creates a new EventsByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEventsByIDGetParamsWithHTTPClient(client *http.Client) *EventsByIDGetParams {
	var ()
	return &EventsByIDGetParams{
		HTTPClient: client,
	}
}

/*EventsByIDGetParams contains all the parameters to send to the API endpoint
for the events by Id get operation typically these are written to a http.Request
*/
type EventsByIDGetParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the events by Id get params
func (o *EventsByIDGetParams) WithTimeout(timeout time.Duration) *EventsByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the events by Id get params
func (o *EventsByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the events by Id get params
func (o *EventsByIDGetParams) WithContext(ctx context.Context) *EventsByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the events by Id get params
func (o *EventsByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the events by Id get params
func (o *EventsByIDGetParams) WithHTTPClient(client *http.Client) *EventsByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the events by Id get params
func (o *EventsByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the events by Id get params
func (o *EventsByIDGetParams) WithID(id string) *EventsByIDGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the events by Id get params
func (o *EventsByIDGetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EventsByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
