// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ChangeaspecificPeeringServerPreferenceReader is a Reader for the ChangeaspecificPeeringServerPreference structure.
type ChangeaspecificPeeringServerPreferenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeaspecificPeeringServerPreferenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewChangeaspecificPeeringServerPreferenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewChangeaspecificPeeringServerPreferenceOK creates a ChangeaspecificPeeringServerPreferenceOK with default headers values
func NewChangeaspecificPeeringServerPreferenceOK() *ChangeaspecificPeeringServerPreferenceOK {
	return &ChangeaspecificPeeringServerPreferenceOK{}
}

/*ChangeaspecificPeeringServerPreferenceOK handles this case with default header values.

ChangeaspecificPeeringServerPreferenceOK changeaspecific peering server preference o k
*/
type ChangeaspecificPeeringServerPreferenceOK struct {
	Payload string
}

func (o *ChangeaspecificPeeringServerPreferenceOK) Error() string {
	return fmt.Sprintf("[PATCH /peeringserverpreferences/{id}][%d] changeaspecificPeeringServerPreferenceOK  %+v", 200, o.Payload)
}

func (o *ChangeaspecificPeeringServerPreferenceOK) GetPayload() string {
	return o.Payload
}

func (o *ChangeaspecificPeeringServerPreferenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
