// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewChangeaspecificPbxDeviceProfileParams creates a new ChangeaspecificPbxDeviceProfileParams object
// with the default values initialized.
func NewChangeaspecificPbxDeviceProfileParams() *ChangeaspecificPbxDeviceProfileParams {
	var ()
	return &ChangeaspecificPbxDeviceProfileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeaspecificPbxDeviceProfileParamsWithTimeout creates a new ChangeaspecificPbxDeviceProfileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeaspecificPbxDeviceProfileParamsWithTimeout(timeout time.Duration) *ChangeaspecificPbxDeviceProfileParams {
	var ()
	return &ChangeaspecificPbxDeviceProfileParams{

		timeout: timeout,
	}
}

// NewChangeaspecificPbxDeviceProfileParamsWithContext creates a new ChangeaspecificPbxDeviceProfileParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeaspecificPbxDeviceProfileParamsWithContext(ctx context.Context) *ChangeaspecificPbxDeviceProfileParams {
	var ()
	return &ChangeaspecificPbxDeviceProfileParams{

		Context: ctx,
	}
}

// NewChangeaspecificPbxDeviceProfileParamsWithHTTPClient creates a new ChangeaspecificPbxDeviceProfileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeaspecificPbxDeviceProfileParamsWithHTTPClient(client *http.Client) *ChangeaspecificPbxDeviceProfileParams {
	var ()
	return &ChangeaspecificPbxDeviceProfileParams{
		HTTPClient: client,
	}
}

/*ChangeaspecificPbxDeviceProfileParams contains all the parameters to send to the API endpoint
for the changeaspecific pbx device profile operation typically these are written to a http.Request
*/
type ChangeaspecificPbxDeviceProfileParams struct {

	/*Body*/
	Body string
	/*ContentType*/
	ContentType string
	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) WithTimeout(timeout time.Duration) *ChangeaspecificPbxDeviceProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) WithContext(ctx context.Context) *ChangeaspecificPbxDeviceProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) WithHTTPClient(client *http.Client) *ChangeaspecificPbxDeviceProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) WithBody(body string) *ChangeaspecificPbxDeviceProfileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) SetBody(body string) {
	o.Body = body
}

// WithContentType adds the contentType to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) WithContentType(contentType string) *ChangeaspecificPbxDeviceProfileParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithID adds the id to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) WithID(id string) *ChangeaspecificPbxDeviceProfileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the changeaspecific pbx device profile params
func (o *ChangeaspecificPbxDeviceProfileParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeaspecificPbxDeviceProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
