// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetaspecificReminderParams creates a new GetaspecificReminderParams object
// with the default values initialized.
func NewGetaspecificReminderParams() *GetaspecificReminderParams {
	var ()
	return &GetaspecificReminderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetaspecificReminderParamsWithTimeout creates a new GetaspecificReminderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetaspecificReminderParamsWithTimeout(timeout time.Duration) *GetaspecificReminderParams {
	var ()
	return &GetaspecificReminderParams{

		timeout: timeout,
	}
}

// NewGetaspecificReminderParamsWithContext creates a new GetaspecificReminderParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetaspecificReminderParamsWithContext(ctx context.Context) *GetaspecificReminderParams {
	var ()
	return &GetaspecificReminderParams{

		Context: ctx,
	}
}

// NewGetaspecificReminderParamsWithHTTPClient creates a new GetaspecificReminderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetaspecificReminderParamsWithHTTPClient(client *http.Client) *GetaspecificReminderParams {
	var ()
	return &GetaspecificReminderParams{
		HTTPClient: client,
	}
}

/*GetaspecificReminderParams contains all the parameters to send to the API endpoint
for the getaspecific reminder operation typically these are written to a http.Request
*/
type GetaspecificReminderParams struct {

	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the getaspecific reminder params
func (o *GetaspecificReminderParams) WithTimeout(timeout time.Duration) *GetaspecificReminderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the getaspecific reminder params
func (o *GetaspecificReminderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the getaspecific reminder params
func (o *GetaspecificReminderParams) WithContext(ctx context.Context) *GetaspecificReminderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the getaspecific reminder params
func (o *GetaspecificReminderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the getaspecific reminder params
func (o *GetaspecificReminderParams) WithHTTPClient(client *http.Client) *GetaspecificReminderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the getaspecific reminder params
func (o *GetaspecificReminderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the getaspecific reminder params
func (o *GetaspecificReminderParams) WithID(id string) *GetaspecificReminderParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the getaspecific reminder params
func (o *GetaspecificReminderParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetaspecificReminderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
