// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReplaceChangeaspecificCustomerBalanceParams creates a new ReplaceChangeaspecificCustomerBalanceParams object
// with the default values initialized.
func NewReplaceChangeaspecificCustomerBalanceParams() *ReplaceChangeaspecificCustomerBalanceParams {
	var ()
	return &ReplaceChangeaspecificCustomerBalanceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceChangeaspecificCustomerBalanceParamsWithTimeout creates a new ReplaceChangeaspecificCustomerBalanceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReplaceChangeaspecificCustomerBalanceParamsWithTimeout(timeout time.Duration) *ReplaceChangeaspecificCustomerBalanceParams {
	var ()
	return &ReplaceChangeaspecificCustomerBalanceParams{

		timeout: timeout,
	}
}

// NewReplaceChangeaspecificCustomerBalanceParamsWithContext creates a new ReplaceChangeaspecificCustomerBalanceParams object
// with the default values initialized, and the ability to set a context for a request
func NewReplaceChangeaspecificCustomerBalanceParamsWithContext(ctx context.Context) *ReplaceChangeaspecificCustomerBalanceParams {
	var ()
	return &ReplaceChangeaspecificCustomerBalanceParams{

		Context: ctx,
	}
}

// NewReplaceChangeaspecificCustomerBalanceParamsWithHTTPClient creates a new ReplaceChangeaspecificCustomerBalanceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReplaceChangeaspecificCustomerBalanceParamsWithHTTPClient(client *http.Client) *ReplaceChangeaspecificCustomerBalanceParams {
	var ()
	return &ReplaceChangeaspecificCustomerBalanceParams{
		HTTPClient: client,
	}
}

/*ReplaceChangeaspecificCustomerBalanceParams contains all the parameters to send to the API endpoint
for the replace changeaspecific customer balance operation typically these are written to a http.Request
*/
type ReplaceChangeaspecificCustomerBalanceParams struct {

	/*Body*/
	Body *Replace1changeaspecificCustomerBalanceRequest
	/*ContentType*/
	ContentType string
	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) WithTimeout(timeout time.Duration) *ReplaceChangeaspecificCustomerBalanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) WithContext(ctx context.Context) *ReplaceChangeaspecificCustomerBalanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) WithHTTPClient(client *http.Client) *ReplaceChangeaspecificCustomerBalanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) WithBody(body *Replace1changeaspecificCustomerBalanceRequest) *ReplaceChangeaspecificCustomerBalanceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) SetBody(body *Replace1changeaspecificCustomerBalanceRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) WithContentType(contentType string) *ReplaceChangeaspecificCustomerBalanceParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithID adds the id to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) WithID(id string) *ReplaceChangeaspecificCustomerBalanceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the replace changeaspecific customer balance params
func (o *ReplaceChangeaspecificCustomerBalanceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceChangeaspecificCustomerBalanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
