// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReplaceChangeaspecificBillingProfileParams creates a new ReplaceChangeaspecificBillingProfileParams object
// with the default values initialized.
func NewReplaceChangeaspecificBillingProfileParams() *ReplaceChangeaspecificBillingProfileParams {
	var ()
	return &ReplaceChangeaspecificBillingProfileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceChangeaspecificBillingProfileParamsWithTimeout creates a new ReplaceChangeaspecificBillingProfileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReplaceChangeaspecificBillingProfileParamsWithTimeout(timeout time.Duration) *ReplaceChangeaspecificBillingProfileParams {
	var ()
	return &ReplaceChangeaspecificBillingProfileParams{

		timeout: timeout,
	}
}

// NewReplaceChangeaspecificBillingProfileParamsWithContext creates a new ReplaceChangeaspecificBillingProfileParams object
// with the default values initialized, and the ability to set a context for a request
func NewReplaceChangeaspecificBillingProfileParamsWithContext(ctx context.Context) *ReplaceChangeaspecificBillingProfileParams {
	var ()
	return &ReplaceChangeaspecificBillingProfileParams{

		Context: ctx,
	}
}

// NewReplaceChangeaspecificBillingProfileParamsWithHTTPClient creates a new ReplaceChangeaspecificBillingProfileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReplaceChangeaspecificBillingProfileParamsWithHTTPClient(client *http.Client) *ReplaceChangeaspecificBillingProfileParams {
	var ()
	return &ReplaceChangeaspecificBillingProfileParams{
		HTTPClient: client,
	}
}

/*ReplaceChangeaspecificBillingProfileParams contains all the parameters to send to the API endpoint
for the replace changeaspecific billing profile operation typically these are written to a http.Request
*/
type ReplaceChangeaspecificBillingProfileParams struct {

	/*Body*/
	Body *Replace1changeaspecificBillingProfileRequest
	/*ContentType*/
	ContentType string
	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) WithTimeout(timeout time.Duration) *ReplaceChangeaspecificBillingProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) WithContext(ctx context.Context) *ReplaceChangeaspecificBillingProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) WithHTTPClient(client *http.Client) *ReplaceChangeaspecificBillingProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) WithBody(body *Replace1changeaspecificBillingProfileRequest) *ReplaceChangeaspecificBillingProfileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) SetBody(body *Replace1changeaspecificBillingProfileRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) WithContentType(contentType string) *ReplaceChangeaspecificBillingProfileParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithID adds the id to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) WithID(id string) *ReplaceChangeaspecificBillingProfileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the replace changeaspecific billing profile params
func (o *ReplaceChangeaspecificBillingProfileParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceChangeaspecificBillingProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
