// Code generated by go-swagger; DO NOT EDIT.

package nr_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReplaceChangeaspecificTrustedSourceParams creates a new ReplaceChangeaspecificTrustedSourceParams object
// with the default values initialized.
func NewReplaceChangeaspecificTrustedSourceParams() *ReplaceChangeaspecificTrustedSourceParams {
	var ()
	return &ReplaceChangeaspecificTrustedSourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceChangeaspecificTrustedSourceParamsWithTimeout creates a new ReplaceChangeaspecificTrustedSourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReplaceChangeaspecificTrustedSourceParamsWithTimeout(timeout time.Duration) *ReplaceChangeaspecificTrustedSourceParams {
	var ()
	return &ReplaceChangeaspecificTrustedSourceParams{

		timeout: timeout,
	}
}

// NewReplaceChangeaspecificTrustedSourceParamsWithContext creates a new ReplaceChangeaspecificTrustedSourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewReplaceChangeaspecificTrustedSourceParamsWithContext(ctx context.Context) *ReplaceChangeaspecificTrustedSourceParams {
	var ()
	return &ReplaceChangeaspecificTrustedSourceParams{

		Context: ctx,
	}
}

// NewReplaceChangeaspecificTrustedSourceParamsWithHTTPClient creates a new ReplaceChangeaspecificTrustedSourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReplaceChangeaspecificTrustedSourceParamsWithHTTPClient(client *http.Client) *ReplaceChangeaspecificTrustedSourceParams {
	var ()
	return &ReplaceChangeaspecificTrustedSourceParams{
		HTTPClient: client,
	}
}

/*ReplaceChangeaspecificTrustedSourceParams contains all the parameters to send to the API endpoint
for the replace changeaspecific trusted source operation typically these are written to a http.Request
*/
type ReplaceChangeaspecificTrustedSourceParams struct {

	/*Body*/
	Body *Replace1changeaspecificTrustedSourceRequest
	/*ContentType*/
	ContentType string
	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) WithTimeout(timeout time.Duration) *ReplaceChangeaspecificTrustedSourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) WithContext(ctx context.Context) *ReplaceChangeaspecificTrustedSourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) WithHTTPClient(client *http.Client) *ReplaceChangeaspecificTrustedSourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) WithBody(body *Replace1changeaspecificTrustedSourceRequest) *ReplaceChangeaspecificTrustedSourceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) SetBody(body *Replace1changeaspecificTrustedSourceRequest) {
	o.Body = body
}

// WithContentType adds the contentType to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) WithContentType(contentType string) *ReplaceChangeaspecificTrustedSourceParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithID adds the id to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) WithID(id string) *ReplaceChangeaspecificTrustedSourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the replace changeaspecific trusted source params
func (o *ReplaceChangeaspecificTrustedSourceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceChangeaspecificTrustedSourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
