// Code generated by go-swagger; DO NOT EDIT.

package callqueues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetaspecificCallQueueParams creates a new GetaspecificCallQueueParams object
// with the default values initialized.
func NewGetaspecificCallQueueParams() *GetaspecificCallQueueParams {
	var ()
	return &GetaspecificCallQueueParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetaspecificCallQueueParamsWithTimeout creates a new GetaspecificCallQueueParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetaspecificCallQueueParamsWithTimeout(timeout time.Duration) *GetaspecificCallQueueParams {
	var ()
	return &GetaspecificCallQueueParams{

		timeout: timeout,
	}
}

// NewGetaspecificCallQueueParamsWithContext creates a new GetaspecificCallQueueParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetaspecificCallQueueParamsWithContext(ctx context.Context) *GetaspecificCallQueueParams {
	var ()
	return &GetaspecificCallQueueParams{

		Context: ctx,
	}
}

// NewGetaspecificCallQueueParamsWithHTTPClient creates a new GetaspecificCallQueueParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetaspecificCallQueueParamsWithHTTPClient(client *http.Client) *GetaspecificCallQueueParams {
	var ()
	return &GetaspecificCallQueueParams{
		HTTPClient: client,
	}
}

/*GetaspecificCallQueueParams contains all the parameters to send to the API endpoint
for the getaspecific call queue operation typically these are written to a http.Request
*/
type GetaspecificCallQueueParams struct {

	/*ID
	  (Required)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the getaspecific call queue params
func (o *GetaspecificCallQueueParams) WithTimeout(timeout time.Duration) *GetaspecificCallQueueParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the getaspecific call queue params
func (o *GetaspecificCallQueueParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the getaspecific call queue params
func (o *GetaspecificCallQueueParams) WithContext(ctx context.Context) *GetaspecificCallQueueParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the getaspecific call queue params
func (o *GetaspecificCallQueueParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the getaspecific call queue params
func (o *GetaspecificCallQueueParams) WithHTTPClient(client *http.Client) *GetaspecificCallQueueParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the getaspecific call queue params
func (o *GetaspecificCallQueueParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the getaspecific call queue params
func (o *GetaspecificCallQueueParams) WithID(id string) *GetaspecificCallQueueParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the getaspecific call queue params
func (o *GetaspecificCallQueueParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetaspecificCallQueueParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
