// Code generated by go-swagger; DO NOT EDIT.

package pbxdeviceprofiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPbxDeviceProfileitemsParams creates a new GetPbxDeviceProfileitemsParams object
// with the default values initialized.
func NewGetPbxDeviceProfileitemsParams() *GetPbxDeviceProfileitemsParams {
	var ()
	return &GetPbxDeviceProfileitemsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPbxDeviceProfileitemsParamsWithTimeout creates a new GetPbxDeviceProfileitemsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPbxDeviceProfileitemsParamsWithTimeout(timeout time.Duration) *GetPbxDeviceProfileitemsParams {
	var ()
	return &GetPbxDeviceProfileitemsParams{

		timeout: timeout,
	}
}

// NewGetPbxDeviceProfileitemsParamsWithContext creates a new GetPbxDeviceProfileitemsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPbxDeviceProfileitemsParamsWithContext(ctx context.Context) *GetPbxDeviceProfileitemsParams {
	var ()
	return &GetPbxDeviceProfileitemsParams{

		Context: ctx,
	}
}

// NewGetPbxDeviceProfileitemsParamsWithHTTPClient creates a new GetPbxDeviceProfileitemsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPbxDeviceProfileitemsParamsWithHTTPClient(client *http.Client) *GetPbxDeviceProfileitemsParams {
	var ()
	return &GetPbxDeviceProfileitemsParams{
		HTTPClient: client,
	}
}

/*GetPbxDeviceProfileitemsParams contains all the parameters to send to the API endpoint
for the get pbx device profileitems operation typically these are written to a http.Request
*/
type GetPbxDeviceProfileitemsParams struct {

	/*ConfigID
	  Filter for profiles matching a config_id

	*/
	ConfigID string
	/*Name
	  Filter for profiles matching a name pattern

	*/
	Name string
	/*OrderBy
	  Order collection by a specific attribute.

	*/
	OrderBy string
	/*OrderByDirection
	  Direction which the collection should be ordered by. Possible values are: asc (default), desc.

	*/
	OrderByDirection string
	/*Page
	  Pagination page which should be displayed (default: 1)

	*/
	Page string
	/*Rows
	  Number of rows in one pagination page (default: 10)

	*/
	Rows string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) WithTimeout(timeout time.Duration) *GetPbxDeviceProfileitemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) WithContext(ctx context.Context) *GetPbxDeviceProfileitemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) WithHTTPClient(client *http.Client) *GetPbxDeviceProfileitemsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfigID adds the configID to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) WithConfigID(configID string) *GetPbxDeviceProfileitemsParams {
	o.SetConfigID(configID)
	return o
}

// SetConfigID adds the configId to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) SetConfigID(configID string) {
	o.ConfigID = configID
}

// WithName adds the name to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) WithName(name string) *GetPbxDeviceProfileitemsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) SetName(name string) {
	o.Name = name
}

// WithOrderBy adds the orderBy to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) WithOrderBy(orderBy string) *GetPbxDeviceProfileitemsParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) SetOrderBy(orderBy string) {
	o.OrderBy = orderBy
}

// WithOrderByDirection adds the orderByDirection to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) WithOrderByDirection(orderByDirection string) *GetPbxDeviceProfileitemsParams {
	o.SetOrderByDirection(orderByDirection)
	return o
}

// SetOrderByDirection adds the orderByDirection to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) SetOrderByDirection(orderByDirection string) {
	o.OrderByDirection = orderByDirection
}

// WithPage adds the page to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) WithPage(page string) *GetPbxDeviceProfileitemsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) SetPage(page string) {
	o.Page = page
}

// WithRows adds the rows to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) WithRows(rows string) *GetPbxDeviceProfileitemsParams {
	o.SetRows(rows)
	return o
}

// SetRows adds the rows to the get pbx device profileitems params
func (o *GetPbxDeviceProfileitemsParams) SetRows(rows string) {
	o.Rows = rows
}

// WriteToRequest writes these params to a swagger request
func (o *GetPbxDeviceProfileitemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param config_id
	qrConfigID := o.ConfigID
	qConfigID := qrConfigID
	if qConfigID != "" {
		if err := r.SetQueryParam("config_id", qConfigID); err != nil {
			return err
		}
	}

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {
		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	// query param order_by
	qrOrderBy := o.OrderBy
	qOrderBy := qrOrderBy
	if qOrderBy != "" {
		if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
			return err
		}
	}

	// query param order_by_direction
	qrOrderByDirection := o.OrderByDirection
	qOrderByDirection := qrOrderByDirection
	if qOrderByDirection != "" {
		if err := r.SetQueryParam("order_by_direction", qOrderByDirection); err != nil {
			return err
		}
	}

	// query param page
	qrPage := o.Page
	qPage := qrPage
	if qPage != "" {
		if err := r.SetQueryParam("page", qPage); err != nil {
			return err
		}
	}

	// query param rows
	qrRows := o.Rows
	qRows := qrRows
	if qRows != "" {
		if err := r.SetQueryParam("rows", qRows); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
