// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReplaceChangeaspecificRtcNetworkRequest Replace/changeaspecificRtcNetworkRequest
// swagger:model Replace/changeaspecificRtcNetworkRequest
type ReplaceChangeaspecificRtcNetworkRequest struct {

	// networks
	// Required: true
	Networks []*Network `json:"networks"`

	// reseller id
	// Required: true
	ResellerID *string `json:"reseller_id"`

	// rtc user id
	// Required: true
	RtcUserID *string `json:"rtc_user_id"`
}

// Validate validates this replace changeaspecific rtc network request
func (m *ReplaceChangeaspecificRtcNetworkRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNetworks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResellerID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRtcUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReplaceChangeaspecificRtcNetworkRequest) validateNetworks(formats strfmt.Registry) error {

	if err := validate.Required("networks", "body", m.Networks); err != nil {
		return err
	}

	for i := 0; i < len(m.Networks); i++ {
		if swag.IsZero(m.Networks[i]) { // not required
			continue
		}

		if m.Networks[i] != nil {
			if err := m.Networks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ReplaceChangeaspecificRtcNetworkRequest) validateResellerID(formats strfmt.Registry) error {

	if err := validate.Required("reseller_id", "body", m.ResellerID); err != nil {
		return err
	}

	return nil
}

func (m *ReplaceChangeaspecificRtcNetworkRequest) validateRtcUserID(formats strfmt.Registry) error {

	if err := validate.Required("rtc_user_id", "body", m.RtcUserID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReplaceChangeaspecificRtcNetworkRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReplaceChangeaspecificRtcNetworkRequest) UnmarshalBinary(b []byte) error {
	var res ReplaceChangeaspecificRtcNetworkRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
