// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReplaceChangeaspecificEmergencyMappingRequest Replace/changeaspecificEmergencyMappingRequest
// swagger:model Replace/changeaspecificEmergencyMappingRequest
type ReplaceChangeaspecificEmergencyMappingRequest struct {

	// code
	// Required: true
	Code *string `json:"code"`

	// emergency container id
	// Required: true
	EmergencyContainerID *string `json:"emergency_container_id"`

	// prefix
	// Required: true
	Prefix *string `json:"prefix"`
}

// Validate validates this replace changeaspecific emergency mapping request
func (m *ReplaceChangeaspecificEmergencyMappingRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmergencyContainerID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrefix(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReplaceChangeaspecificEmergencyMappingRequest) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", m.Code); err != nil {
		return err
	}

	return nil
}

func (m *ReplaceChangeaspecificEmergencyMappingRequest) validateEmergencyContainerID(formats strfmt.Registry) error {

	if err := validate.Required("emergency_container_id", "body", m.EmergencyContainerID); err != nil {
		return err
	}

	return nil
}

func (m *ReplaceChangeaspecificEmergencyMappingRequest) validatePrefix(formats strfmt.Registry) error {

	if err := validate.Required("prefix", "body", m.Prefix); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReplaceChangeaspecificEmergencyMappingRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReplaceChangeaspecificEmergencyMappingRequest) UnmarshalBinary(b []byte) error {
	var res ReplaceChangeaspecificEmergencyMappingRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
